In [3]:
import cv2
import numpy as np
import re

from PIL import Image
from PIL import ImageDraw
from PIL import ImageColor
from PIL import ImageFont

vidcap = cv2.VideoCapture('video_nurbu.mp4')
success,imagenBruta = vidcap.read()

while success:
    #resize image
    img = cv2.resize(imagenBruta,(320, 320))
    input_data = np.expand_dims(img, axis=0)
    image = Image.fromarray(imagenBruta)
    
    draw = ImageDraw.Draw(image)
    im_w, im_h = image.size
    print(image.size)
    
    cv2.imshow('Video Test', np.array(image, dtype = np.uint8))
    #Wait. Also exits when q key is pressed. Needed to show the video, DO NOT DELETE.
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    
    success,imagenBruta = vidcap.read()
    
    
vidcap.release()
cv2.destroyAllWindows()


(320, 320)
[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[ 3  0  1]
  [ 3  0  1]
  [ 3  0  1]
  ...
  [11  1  3]
  [11  1  3]
  [11  1  3]]

 [[18  1  4]
  [18  1  4]
  [18  1  4]
  ...
  [18  3  6]
  [18  3  6]
  [18  3  6]]

 [[20  3  6]
  [20  3  6]
  [20  3  6]
  ...
  [21  6  9]
  [21  6  9]
  [21  6  9]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
 

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(320, 320)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0

(320, 320)
[[[25 25 25]
  [25 25 25]
  [26 26 26]
  ...
  [44 44 44]
  [41 41 41]
  [40 40 40]]

 [[25 25 25]
  [25 25 25]
  [26 26 26]
  ...
  [44 44 44]
  [41 41 41]
  [39 39 39]]

 [[25 25 25]
  [25 25 25]
  [26 26 26]
  ...
  [44 44 44]
  [41 41 41]
  [39 39 39]]

 ...

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]]
(320, 320)
[[[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [40 40 40]]

 [[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [39 39 39]]

 [[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [39 39 39]]

 ...

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[25 25 25]
  [26 2

[[[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [40 40 40]]

 [[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [39 39 39]]

 [[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [39 39 39]]

 ...

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]]
(320, 320)
[[[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [40 40 40]]

 [[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [39 39 39]]

 [[24 24 24]
  [25 25 25]
  [25 25 25]
  ...
  [44 44 44]
  [41 41 41]
  [39 39 39]]

 ...

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[25 25 25]
  [26 26 26]
  [29 29 29]
  ...
  [24 24 24]
  [24 24 24]
  [24 24 24]]

 [[25 25 25]
  [26 26 26]
  [29

[[[13 13 13]
  [13 13 13]
  [13 13 13]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[13 13 13]
  [13 13 13]
  [13 13 13]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[13 13 13]
  [13 13 13]
  [13 13 13]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 ...

 [[13 13 13]
  [13 13 13]
  [13 13 13]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[13 13 13]
  [13 13 13]
  [13 13 13]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]

 [[13 13 13]
  [13 13 13]
  [13 13 13]
  ...
  [10 10 10]
  [10 10 10]
  [10 10 10]]]
(320, 320)
[[[ 8  8  8]
  [ 8  8  8]
  [ 9  9  9]
  ...
  [15 15 15]
  [15 15 15]
  [15 15 15]]

 [[ 8  8  8]
  [ 8  8  8]
  [ 9  9  9]
  ...
  [15 15 15]
  [15 15 15]
  [15 15 15]]

 [[ 8  8  8]
  [ 8  8  8]
  [ 9  9  9]
  ...
  [15 15 15]
  [15 15 15]
  [15 15 15]]

 ...

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [ 8  8  8]
  [ 8  8  8]
  [ 8  8  8]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [ 8  8  8]
  [ 8  8  8]
  [ 8  8  8]]

 [[10 10 10]
  [10 10 10]
  [10

[[[ 45  81  87]
  [ 31  67  73]
  [ 30  66  72]
  ...
  [ 30  41  35]
  [ 30  41  35]
  [ 30  41  35]]

 [[ 45  81  87]
  [ 32  68  74]
  [ 29  65  71]
  ...
  [ 30  41  35]
  [ 30  41  35]
  [ 30  41  35]]

 [[ 39  75  81]
  [ 33  69  75]
  [ 30  66  72]
  ...
  [ 29  40  34]
  [ 29  40  34]
  [ 29  40  34]]

 ...

 [[ 40  53  61]
  [ 45  58  66]
  [ 45  61  68]
  ...
  [126 129 127]
  [126 129 127]
  [126 129 127]]

 [[ 39  52  60]
  [ 43  56  64]
  [ 43  59  66]
  ...
  [132 135 133]
  [132 135 133]
  [132 135 133]]

 [[ 37  50  58]
  [ 39  52  60]
  [ 41  57  64]
  ...
  [134 137 135]
  [134 137 135]
  [134 137 135]]]
(320, 320)
[[[ 30  66  72]
  [ 33  69  75]
  [ 52  88  94]
  ...
  [ 34  42  39]
  [ 36  44  41]
  [ 36  44  41]]

 [[ 30  66  72]
  [ 32  68  74]
  [ 53  89  95]
  ...
  [ 34  42  39]
  [ 36  44  41]
  [ 36  44  41]]

 [[ 32  68  74]
  [ 32  68  74]
  [ 54  90  96]
  ...
  [ 33  41  38]
  [ 34  42  39]
  [ 34  42  39]]

 ...

 [[ 44  60  67]
  [ 47  63  70]
  [ 45  6

[[[ 42  50  59]
  [ 43  51  60]
  [ 44  52  61]
  ...
  [ 72  92  89]
  [ 65  85  82]
  [ 62  82  79]]

 [[ 40  48  57]
  [ 40  48  57]
  [ 39  47  56]
  ...
  [ 66  86  83]
  [ 63  83  80]
  [ 62  82  79]]

 [[ 39  46  57]
  [ 39  46  57]
  [ 37  44  55]
  ...
  [ 70  92  89]
  [ 74  96  93]
  [ 75  97  94]]

 ...

 [[ 42  71  73]
  [ 40  69  71]
  [ 45  74  76]
  ...
  [ 81 111 116]
  [ 80 110 115]
  [ 79 109 114]]

 [[ 41  70  72]
  [ 39  68  70]
  [ 44  73  75]
  ...
  [ 82 112 112]
  [ 81 111 111]
  [ 81 111 111]]

 [[ 41  70  72]
  [ 39  68  70]
  [ 44  73  75]
  ...
  [ 83 113 113]
  [ 82 112 112]
  [ 82 112 112]]]
(320, 320)
[[[ 41  49  58]
  [ 41  49  58]
  [ 37  48  56]
  ...
  [ 67  82  80]
  [ 95 110 108]
  [124 139 137]]

 [[ 37  45  54]
  [ 36  44  53]
  [ 34  45  53]
  ...
  [ 82  97  95]
  [ 96 111 109]
  [110 125 123]]

 [[ 41  48  59]
  [ 35  42  53]
  [ 32  43  51]
  ...
  [122 138 138]
  [109 125 125]
  [ 94 110 110]]

 ...

 [[ 45  74  76]
  [ 51  80  82]
  [ 52  8

(320, 320)
[[[ 56  91  81]
  [ 52  87  77]
  [ 45  85  74]
  ...
  [150 185 209]
  [150 185 209]
  [150 185 209]]

 [[ 58  93  83]
  [ 56  91  81]
  [ 50  90  79]
  ...
  [149 184 208]
  [149 184 208]
  [149 184 208]]

 [[ 66  93  87]
  [ 65  92  86]
  [ 60  92  85]
  ...
  [149 183 210]
  [149 183 210]
  [149 183 210]]

 ...

 [[ 28  34  43]
  [ 29  35  44]
  [ 30  36  45]
  ...
  [110 116 111]
  [ 92  98  93]
  [ 92  98  93]]

 [[ 28  34  43]
  [ 29  35  44]
  [ 30  36  45]
  ...
  [103 109 104]
  [ 99 105 100]
  [ 99 105 100]]

 [[ 28  34  43]
  [ 29  35  44]
  [ 30  36  45]
  ...
  [103 109 104]
  [ 99 105 100]
  [ 99 105 100]]]
(320, 320)
[[[ 64  93  87]
  [ 62  91  85]
  [ 57  91  84]
  ...
  [146 186 209]
  [146 186 209]
  [146 186 209]]

 [[ 65  94  88]
  [ 68  97  91]
  [ 64  98  91]
  ...
  [146 186 209]
  [146 186 209]
  [146 186 209]]

 [[ 78  98  93]
  [ 84 104  99]
  [ 81 105 100]
  ...
  [146 186 209]
  [146 186 209]
  [146 186 209]]

 ...

 [[ 29  35  44]
  [ 29  35  44

(320, 320)
[[[ 91  83  83]
  [ 89  81  81]
  [ 89  81  81]
  ...
  [108 147 159]
  [110 149 161]
  [110 149 161]]

 [[ 92  84  84]
  [ 91  83  83]
  [ 92  84  84]
  ...
  [107 146 158]
  [108 147 159]
  [108 147 159]]

 [[ 94  86  86]
  [ 94  86  86]
  [ 92  84  84]
  ...
  [103 140 152]
  [105 142 154]
  [105 142 154]]

 ...

 [[ 32  44  49]
  [ 34  46  51]
  [ 25  37  42]
  ...
  [ 94  89  88]
  [ 94  89  88]
  [ 94  89  88]]

 [[ 31  43  48]
  [ 33  45  50]
  [ 25  37  42]
  ...
  [ 93  88  87]
  [ 93  88  87]
  [ 93  88  87]]

 [[ 31  43  48]
  [ 33  45  50]
  [ 25  37  42]
  ...
  [ 93  88  87]
  [ 93  88  87]
  [ 93  88  87]]]
(320, 320)
[[[ 91  83  83]
  [ 89  81  81]
  [ 89  81  81]
  ...
  [108 145 157]
  [102 139 151]
  [100 137 149]]

 [[ 92  84  84]
  [ 91  83  83]
  [ 92  84  84]
  ...
  [ 96 133 145]
  [ 91 128 140]
  [ 88 125 137]]

 [[ 94  86  86]
  [ 94  86  86]
  [ 92  84  84]
  ...
  [100 133 149]
  [ 94 127 143]
  [ 91 124 140]]

 ...

 [[ 23  37  42]
  [ 35  49  54

[[[ 51  93  91]
  [ 49  91  89]
  [ 48  94  87]
  ...
  [ 75  96 122]
  [ 75  96 122]
  [ 75  96 122]]

 [[ 54  96  94]
  [ 51  93  91]
  [ 49  95  88]
  ...
  [ 74  95 121]
  [ 74  95 121]
  [ 74  95 121]]

 [[ 60 100  96]
  [ 56  96  92]
  [ 53  97  88]
  ...
  [ 61  84 103]
  [ 61  84 103]
  [ 61  84 103]]

 ...

 [[ 40  59  68]
  [ 38  57  66]
  [ 38  57  66]
  ...
  [103 100  99]
  [103 100  99]
  [103 100  99]]

 [[ 40  59  68]
  [ 38  57  66]
  [ 38  57  66]
  ...
  [103 100  99]
  [103 100  99]
  [103 100  99]]

 [[ 40  59  68]
  [ 38  57  66]
  [ 38  57  66]
  ...
  [103 100  99]
  [103 100  99]
  [103 100  99]]]
(320, 320)
[[[ 57  95  91]
  [ 54  92  88]
  [ 54  88  88]
  ...
  [ 66  82 101]
  [ 75  91 110]
  [ 80  96 115]]

 [[ 58  96  92]
  [ 57  95  91]
  [ 57  91  91]
  ...
  [ 66  82 101]
  [ 75  91 110]
  [ 80  96 115]]

 [[ 64  96  96]
  [ 66  98  98]
  [ 69  98 100]
  ...
  [ 54  72  86]
  [ 64  82  96]
  [ 68  86 100]]

 ...

 [[ 43  63  70]
  [ 40  60  67]
  [ 40  5

[[[ 53  93  82]
  [ 53  93  82]
  [ 53  93  82]
  ...
  [ 74 102 119]
  [ 81 109 126]
  [ 58  86 103]]

 [[ 54  94  83]
  [ 53  93  82]
  [ 53  93  82]
  ...
  [ 70  98 115]
  [ 77 105 122]
  [ 66  94 111]]

 [[ 52  94  83]
  [ 51  93  82]
  [ 53  93  82]
  ...
  [ 60  88 105]
  [ 66  94 111]
  [ 84 112 129]]

 ...

 [[ 38  91  67]
  [ 38  91  67]
  [ 37  93  68]
  ...
  [112 109 108]
  [112 109 108]
  [112 109 108]]

 [[ 38  91  67]
  [ 38  91  67]
  [ 37  93  68]
  ...
  [112 109 108]
  [112 109 108]
  [112 109 108]]

 [[ 38  91  67]
  [ 38  91  67]
  [ 37  93  68]
  ...
  [112 109 108]
  [112 109 108]
  [112 109 108]]]
(320, 320)
[[[ 53  93  82]
  [ 49  89  78]
  [ 48  88  77]
  ...
  [ 87 117 129]
  [ 85 115 127]
  [ 85 115 127]]

 [[ 52  92  81]
  [ 49  89  78]
  [ 47  87  76]
  ...
  [ 87 117 129]
  [ 88 118 130]
  [ 90 120 132]]

 [[ 50  90  79]
  [ 50  90  79]
  [ 49  89  78]
  ...
  [ 67  96 110]
  [ 78 107 121]
  [ 83 112 126]]

 ...

 [[ 40  93  69]
  [ 41  94  70]
  [ 41  9

[[[ 39 107  87]
  [ 39 107  87]
  [ 39 107  87]
  ...
  [ 56  72  79]
  [ 57  73  80]
  [ 57  73  80]]

 [[ 34 102  82]
  [ 34 102  82]
  [ 35 103  83]
  ...
  [ 54  70  77]
  [ 55  71  78]
  [ 55  71  78]]

 [[ 30  92  76]
  [ 30  92  76]
  [ 35  97  81]
  ...
  [ 49  65  72]
  [ 49  65  72]
  [ 49  65  72]]

 ...

 [[105 102  96]
  [105 102  96]
  [105 102  96]
  ...
  [ 44  80  73]
  [ 44  80  73]
  [ 44  80  73]]

 [[104 101  95]
  [104 101  95]
  [104 101  95]
  ...
  [ 43  79  72]
  [ 43  79  72]
  [ 43  79  72]]

 [[104 101  95]
  [104 101  95]
  [104 101  95]
  ...
  [ 43  79  72]
  [ 43  79  72]
  [ 43  79  72]]]
(320, 320)
[[[ 41  98  84]
  [ 41  98  84]
  [ 41  98  84]
  ...
  [ 48  64  71]
  [ 49  65  72]
  [ 49  65  72]]

 [[ 42  99  85]
  [ 42  99  85]
  [ 42  99  85]
  ...
  [ 44  60  67]
  [ 41  57  64]
  [ 41  57  64]]

 [[ 54 100  91]
  [ 54 100  91]
  [ 51  97  88]
  ...
  [ 51  67  74]
  [ 43  59  66]
  [ 38  54  61]]

 ...

 [[ 98  95  89]
  [ 99  96  90]
  [ 99  9

[[[ 16  28  25]
  [ 16  28  25]
  [ 16  28  25]
  ...
  [ 54  81  82]
  [ 55  82  83]
  [ 56  83  84]]

 [[ 16  28  25]
  [ 16  28  25]
  [ 16  28  25]
  ...
  [ 54  81  82]
  [ 55  82  83]
  [ 56  83  84]]

 [[ 18  30  27]
  [ 18  30  27]
  [ 18  30  27]
  ...
  [ 53  79  82]
  [ 54  81  82]
  [ 55  82  83]]

 ...

 [[157 159 161]
  [156 158 160]
  [151 153 155]
  ...
  [ 73  97 105]
  [ 70  97 106]
  [ 70  97 106]]

 [[154 156 158]
  [153 155 157]
  [148 150 152]
  ...
  [ 69  93 101]
  [ 65  94 103]
  [ 66  95 104]]

 [[140 142 144]
  [139 141 143]
  [134 136 138]
  ...
  [ 65  89  97]
  [ 61  90  99]
  [ 62  91 100]]]
(320, 320)
[[[ 20  35  33]
  [ 19  34  32]
  [ 14  29  27]
  ...
  [ 51  76  82]
  [ 49  74  80]
  [ 50  75  81]]

 [[ 20  35  33]
  [ 19  34  32]
  [ 16  31  29]
  ...
  [ 50  75  81]
  [ 49  74  80]
  [ 49  74  80]]

 [[ 20  35  33]
  [ 19  34  32]
  [ 14  29  27]
  ...
  [ 50  75  81]
  [ 49  74  80]
  [ 49  74  80]]

 ...

 [[161 163 170]
  [168 170 177]
  [170 17

[[[247 252 252]
  [247 252 252]
  [247 252 252]
  ...
  [ 28  39  40]
  [ 28  39  40]
  [ 27  38  39]]

 [[247 252 252]
  [247 252 252]
  [247 252 252]
  ...
  [ 28  39  40]
  [ 27  38  39]
  [ 27  38  39]]

 [[247 252 252]
  [247 252 252]
  [247 252 252]
  ...
  [ 28  39  40]
  [ 27  38  39]
  [ 27  38  39]]

 ...

 [[ 88 126 136]
  [ 88 126 136]
  [ 88 126 136]
  ...
  [119 122 122]
  [118 120 122]
  [118 120 122]]

 [[ 95 130 141]
  [ 95 130 141]
  [ 95 130 141]
  ...
  [121 123 125]
  [118 120 122]
  [116 118 120]]

 [[ 87 122 133]
  [ 87 122 133]
  [ 88 123 134]
  ...
  [122 124 126]
  [121 123 125]
  [120 122 124]]]
(320, 320)
[[[249 249 249]
  [249 249 249]
  [249 249 249]
  ...
  [ 24  33  34]
  [ 25  36  37]
  [ 23  34  35]]

 [[244 244 244]
  [244 244 244]
  [244 244 244]
  ...
  [ 23  32  33]
  [ 23  34  35]
  [ 22  33  34]]

 [[245 245 245]
  [245 245 245]
  [248 248 248]
  ...
  [ 23  32  33]
  [ 24  33  34]
  [ 24  33  34]]

 ...

 [[ 70 105 116]
  [ 73 108 119]
  [ 76 11

[[[ 32  41  35]
  [ 32  41  35]
  [ 32  41  35]
  ...
  [ 18  23  23]
  [ 22  27  27]
  [ 24  29  29]]

 [[ 32  41  35]
  [ 32  41  35]
  [ 32  41  35]
  ...
  [ 18  23  23]
  [ 22  27  27]
  [ 24  29  29]]

 [[ 32  41  35]
  [ 32  41  35]
  [ 32  41  35]
  ...
  [ 18  23  23]
  [ 22  27  27]
  [ 24  29  29]]

 ...

 [[117 114 121]
  [118 115 122]
  [112 109 116]
  ...
  [118 118 116]
  [122 122 120]
  [126 126 124]]

 [[127 127 134]
  [130 130 137]
  [120 120 127]
  ...
  [121 121 119]
  [122 122 120]
  [129 129 127]]

 [[130 130 137]
  [135 135 142]
  [120 120 127]
  ...
  [119 119 117]
  [122 122 120]
  [128 128 126]]]
(320, 320)
[[[ 29  38  32]
  [ 29  38  32]
  [ 30  39  33]
  ...
  [ 10  15  15]
  [  8  13  13]
  [ 11  16  16]]

 [[ 29  38  32]
  [ 29  38  32]
  [ 30  39  33]
  ...
  [ 10  15  15]
  [  8  13  13]
  [ 11  16  16]]

 [[ 29  38  32]
  [ 29  38  32]
  [ 30  39  33]
  ...
  [ 10  15  15]
  [  8  13  13]
  [ 11  16  16]]

 ...

 [[117 113 123]
  [112 108 118]
  [103  9

[[[ 59  73  73]
  [ 46  60  60]
  [ 32  39  40]
  ...
  [ 24  44  41]
  [ 40  62  59]
  [ 46  68  65]]

 [[ 55  69  69]
  [ 46  60  60]
  [ 32  39  40]
  ...
  [ 40  60  57]
  [ 34  56  53]
  [ 32  54  51]]

 [[ 47  61  61]
  [ 40  54  54]
  [ 32  39  40]
  ...
  [ 44  64  61]
  [ 18  40  37]
  [ 21  43  40]]

 ...

 [[119 122 122]
  [123 126 126]
  [130 133 133]
  ...
  [155 153 149]
  [155 153 149]
  [155 153 149]]

 [[118 121 121]
  [123 126 126]
  [132 135 135]
  ...
  [151 152 147]
  [151 152 147]
  [151 152 147]]

 [[119 122 122]
  [125 128 128]
  [132 135 135]
  ...
  [142 143 138]
  [142 143 138]
  [142 143 138]]]
(320, 320)
[[[ 58  70  69]
  [ 43  55  54]
  [ 31  36  36]
  ...
  [ 19  39  36]
  [ 43  65  62]
  [ 47  69  66]]

 [[ 56  68  67]
  [ 43  55  54]
  [ 31  36  36]
  ...
  [ 43  63  60]
  [ 29  51  48]
  [ 42  64  61]]

 [[ 48  60  59]
  [ 39  51  50]
  [ 31  36  36]
  ...
  [ 44  64  61]
  [ 27  49  46]
  [ 32  54  51]]

 ...

 [[120 123 123]
  [123 126 126]
  [130 13

[[[ 33  33  33]
  [ 32  32  32]
  [ 39  36  37]
  ...
  [ 33  91  82]
  [ 34  90  81]
  [ 35  91  82]]

 [[ 31  31  31]
  [ 31  31  31]
  [ 40  37  38]
  ...
  [ 33  91  82]
  [ 35  91  82]
  [ 36  92  83]]

 [[ 26  26  26]
  [ 30  30  30]
  [ 41  38  39]
  ...
  [ 40  93  85]
  [ 42  93  85]
  [ 43  94  86]]

 ...

 [[125 127 129]
  [125 127 129]
  [128 130 132]
  ...
  [166 175 169]
  [166 175 169]
  [166 175 169]]

 [[129 131 133]
  [128 130 132]
  [128 130 132]
  ...
  [165 170 163]
  [165 170 163]
  [165 170 163]]

 [[130 132 134]
  [130 132 134]
  [129 131 133]
  ...
  [147 152 145]
  [148 153 146]
  [148 153 146]]]
(320, 320)
[[[ 43  46  46]
  [ 41  44  44]
  [ 40  40  40]
  ...
  [ 33  91  82]
  [ 34  90  81]
  [ 35  91  82]]

 [[ 37  40  40]
  [ 38  41  41]
  [ 39  39  39]
  ...
  [ 33  91  82]
  [ 34  90  81]
  [ 35  91  82]]

 [[ 28  31  31]
  [ 33  36  36]
  [ 41  41  41]
  ...
  [ 38  91  83]
  [ 42  93  85]
  [ 43  94  86]]

 ...

 [[135 137 139]
  [134 136 138]
  [140 14

[[[ 20  28  27]
  [ 24  32  31]
  [ 34  39  39]
  ...
  [  3  30  24]
  [ 20  49  43]
  [ 37  66  60]]

 [[ 20  28  27]
  [ 23  31  30]
  [ 32  37  37]
  ...
  [  3  30  24]
  [ 20  49  43]
  [ 37  66  60]]

 [[ 22  30  29]
  [ 22  30  29]
  [ 27  32  32]
  ...
  [  7  34  28]
  [ 25  54  48]
  [ 42  71  65]]

 ...

 [[147 150 150]
  [147 150 150]
  [146 149 149]
  ...
  [183 186 186]
  [173 176 176]
  [172 175 175]]

 [[147 149 151]
  [147 149 151]
  [146 149 149]
  ...
  [148 152 154]
  [140 144 146]
  [139 143 145]]

 [[147 149 151]
  [147 149 151]
  [146 149 149]
  ...
  [147 151 153]
  [146 150 152]
  [146 150 152]]]
(320, 320)
[[[ 20  28  27]
  [ 24  32  31]
  [ 34  39  39]
  ...
  [  3  30  24]
  [ 20  49  43]
  [ 37  66  60]]

 [[ 20  28  27]
  [ 23  31  30]
  [ 32  37  37]
  ...
  [  3  30  24]
  [ 20  49  43]
  [ 37  66  60]]

 [[ 22  30  29]
  [ 22  30  29]
  [ 27  32  32]
  ...
  [  7  34  28]
  [ 25  54  48]
  [ 42  71  65]]

 ...

 [[147 150 150]
  [147 150 150]
  [146 14

[[[ 32  89  82]
  [ 29  86  79]
  [ 42  99  92]
  ...
  [ 35  53  60]
  [ 29  45  52]
  [ 38  54  61]]

 [[ 39  96  89]
  [ 30  87  80]
  [ 33  90  83]
  ...
  [ 35  53  60]
  [ 29  45  52]
  [ 38  54  61]]

 [[ 44 101  94]
  [ 32  89  82]
  [ 40  97  90]
  ...
  [ 36  52  59]
  [ 32  45  53]
  [ 43  56  64]]

 ...

 [[ 44  82  83]
  [ 26  64  65]
  [ 47  83  84]
  ...
  [104 116 121]
  [108 117 123]
  [115 124 130]]

 [[ 49  94  94]
  [ 55 100 100]
  [ 55  98  98]
  ...
  [119 128 134]
  [115 120 126]
  [111 116 122]]

 [[ 31  76  76]
  [ 57 102 102]
  [ 57 100 100]
  ...
  [139 148 154]
  [126 131 137]
  [108 113 119]]]
(320, 320)
[[[ 32  89  82]
  [ 29  86  79]
  [ 42  99  92]
  ...
  [ 35  53  60]
  [ 29  45  52]
  [ 38  54  61]]

 [[ 39  96  89]
  [ 30  87  80]
  [ 33  90  83]
  ...
  [ 35  53  60]
  [ 29  45  52]
  [ 38  54  61]]

 [[ 44 101  94]
  [ 32  89  82]
  [ 40  97  90]
  ...
  [ 36  52  59]
  [ 32  45  53]
  [ 43  56  64]]

 ...

 [[ 44  82  83]
  [ 26  64  65]
  [ 47  8

[[[ 35  91  82]
  [ 29  85  76]
  [ 44  97  89]
  ...
  [ 43  58  61]
  [ 33  48  51]
  [ 37  52  55]]

 [[ 38  94  85]
  [ 26  82  73]
  [ 34  87  79]
  ...
  [ 42  57  60]
  [ 32  47  50]
  [ 38  53  56]]

 [[ 56 116 107]
  [ 30  90  81]
  [ 45 103  94]
  ...
  [ 40  53  56]
  [ 30  43  46]
  [ 40  53  56]]

 ...

 [[ 50  86  87]
  [ 25  61  62]
  [ 51  84  86]
  ...
  [103 118 121]
  [106 121 124]
  [106 121 124]]

 [[ 34  94  91]
  [ 44 104 101]
  [ 42  97  95]
  ...
  [121 131 135]
  [115 121 125]
  [115 121 125]]

 [[ 25  85  82]
  [ 48 108 105]
  [ 45 100  98]
  ...
  [138 148 152]
  [125 131 135]
  [111 117 121]]]
(320, 320)
[[[ 35  91  82]
  [ 29  85  76]
  [ 44  97  89]
  ...
  [ 43  58  61]
  [ 33  48  51]
  [ 37  52  55]]

 [[ 38  94  85]
  [ 26  82  73]
  [ 34  87  79]
  ...
  [ 42  57  60]
  [ 32  47  50]
  [ 38  53  56]]

 [[ 56 116 107]
  [ 30  90  81]
  [ 45 103  94]
  ...
  [ 40  53  56]
  [ 30  43  46]
  [ 40  53  56]]

 ...

 [[ 50  86  87]
  [ 25  61  62]
  [ 51  8

(320, 320)
[[[ 35  91  82]
  [ 29  85  76]
  [ 44  97  89]
  ...
  [ 43  58  61]
  [ 33  48  51]
  [ 37  52  55]]

 [[ 38  94  85]
  [ 26  82  73]
  [ 34  87  79]
  ...
  [ 42  57  60]
  [ 32  47  50]
  [ 38  53  56]]

 [[ 56 116 107]
  [ 30  90  81]
  [ 45 103  94]
  ...
  [ 40  53  56]
  [ 30  43  46]
  [ 40  53  56]]

 ...

 [[ 50  86  87]
  [ 25  61  62]
  [ 51  84  86]
  ...
  [103 118 121]
  [106 121 124]
  [106 121 124]]

 [[ 34  94  91]
  [ 44 104 101]
  [ 42  97  95]
  ...
  [121 131 135]
  [115 121 125]
  [115 121 125]]

 [[ 25  85  82]
  [ 48 108 105]
  [ 45 100  98]
  ...
  [138 148 152]
  [125 131 135]
  [111 117 121]]]
(320, 320)
[[[ 35  91  82]
  [ 29  85  76]
  [ 44  97  89]
  ...
  [ 43  58  61]
  [ 33  48  51]
  [ 37  52  55]]

 [[ 38  94  85]
  [ 26  82  73]
  [ 34  87  79]
  ...
  [ 42  57  60]
  [ 32  47  50]
  [ 38  53  56]]

 [[ 56 116 107]
  [ 30  90  81]
  [ 45 103  94]
  ...
  [ 40  53  56]
  [ 30  43  46]
  [ 40  53  56]]

 ...

 [[ 50  86  87]
  [ 25  61  62

(320, 320)
[[[ 35  90  83]
  [ 29  84  77]
  [ 44  96  90]
  ...
  [ 43  58  61]
  [ 33  48  51]
  [ 37  52  55]]

 [[ 38  93  86]
  [ 26  81  74]
  [ 34  86  80]
  ...
  [ 42  57  60]
  [ 32  47  50]
  [ 38  53  56]]

 [[ 56 115 108]
  [ 30  89  82]
  [ 45 102  95]
  ...
  [ 40  53  56]
  [ 30  43  46]
  [ 40  53  56]]

 ...

 [[ 50  86  87]
  [ 25  61  62]
  [ 51  84  86]
  ...
  [103 118 121]
  [106 121 124]
  [106 121 124]]

 [[ 34  94  91]
  [ 44 104 101]
  [ 42  97  95]
  ...
  [121 131 135]
  [115 121 125]
  [115 121 125]]

 [[ 25  85  82]
  [ 48 108 105]
  [ 45 100  98]
  ...
  [138 148 152]
  [125 131 135]
  [111 117 121]]]
(320, 320)
[[[ 35  90  83]
  [ 29  84  77]
  [ 44  96  90]
  ...
  [ 43  58  61]
  [ 33  48  51]
  [ 37  52  55]]

 [[ 38  93  86]
  [ 26  81  74]
  [ 34  86  80]
  ...
  [ 42  57  60]
  [ 32  47  50]
  [ 38  53  56]]

 [[ 56 115 108]
  [ 30  89  82]
  [ 45 102  95]
  ...
  [ 40  53  56]
  [ 30  43  46]
  [ 40  53  56]]

 ...

 [[ 50  86  87]
  [ 25  61  62

[[[ 95  86  90]
  [ 96  87  91]
  [ 96  87  91]
  ...
  [202 173 162]
  [171 135 125]
  [122  86  76]]

 [[ 95  86  90]
  [ 96  87  91]
  [ 96  87  91]
  ...
  [201 172 161]
  [170 134 124]
  [121  85  75]]

 [[ 95  86  90]
  [ 96  87  91]
  [ 96  87  91]
  ...
  [180 170 156]
  [149 132 119]
  [100  83  70]]

 ...

 [[ 50  96  87]
  [ 51  97  88]
  [ 40  91  81]
  ...
  [136 141 147]
  [136 141 147]
  [136 141 147]]

 [[ 55 101  92]
  [ 55 101  92]
  [ 45  96  86]
  ...
  [142 147 153]
  [143 148 154]
  [143 148 154]]

 [[ 65 111 102]
  [ 65 111 102]
  [ 55 106  96]
  ...
  [136 141 147]
  [136 141 147]
  [136 141 147]]]
(320, 320)
[[[ 96  87  91]
  [ 96  87  91]
  [ 96  87  91]
  ...
  [ 65  42  33]
  [ 93  70  61]
  [102  79  70]]

 [[ 95  86  90]
  [ 96  87  91]
  [ 96  87  91]
  ...
  [ 75  52  43]
  [103  80  71]
  [103  80  71]]

 [[ 95  86  90]
  [ 95  86  90]
  [ 95  86  90]
  ...
  [ 89  73  71]
  [117 101  99]
  [101  85  83]]

 ...

 [[ 55 106  98]
  [ 59 110 102]
  [ 66 11

(320, 320)
[[[ 93  83  90]
  [ 93  83  90]
  [ 89  84  90]
  ...
  [ 79  96 112]
  [ 69  94 108]
  [ 68  93 107]]

 [[ 94  84  91]
  [ 94  84  91]
  [ 90  85  91]
  ...
  [ 76  93 109]
  [ 77 102 116]
  [ 80 105 119]]

 [[ 90  84  87]
  [ 91  85  88]
  [ 91  85  88]
  ...
  [101 120 131]
  [ 75  99 109]
  [ 64  88  98]]

 ...

 [[ 51  86  83]
  [ 50  85  82]
  [ 51  91  87]
  ...
  [ 87  83  86]
  [ 87  83  86]
  [ 87  83  86]]

 [[ 50  85  82]
  [ 49  84  81]
  [ 50  90  86]
  ...
  [ 87  83  86]
  [ 87  83  86]
  [ 87  83  86]]

 [[ 50  85  82]
  [ 49  84  81]
  [ 50  90  86]
  ...
  [ 87  83  86]
  [ 87  83  86]
  [ 87  83  86]]]
(320, 320)
[[[ 85  79  87]
  [102  96 104]
  [143 138 152]
  ...
  [ 70  88 102]
  [ 52  70  84]
  [ 43  61  75]]

 [[ 87  81  89]
  [ 91  85  93]
  [110 105 119]
  ...
  [ 58  76  90]
  [ 45  63  77]
  [ 38  56  70]]

 [[ 95  88  94]
  [ 94  87  93]
  [ 97  90 101]
  ...
  [ 63  87  95]
  [ 57  81  89]
  [ 56  80  88]]

 ...

 [[ 52  92  88]
  [ 46  86  82

(320, 320)
[[[ 62 123 118]
  [ 62 123 118]
  [ 64 125 120]
  ...
  [ 40  71  78]
  [ 45  76  83]
  [ 43  74  81]]

 [[ 61 122 117]
  [ 61 122 117]
  [ 62 123 118]
  ...
  [ 41  72  79]
  [ 47  78  85]
  [ 44  75  82]]

 [[ 61 122 117]
  [ 59 120 115]
  [ 61 123 115]
  ...
  [ 40  70  75]
  [ 45  75  80]
  [ 43  73  78]]

 ...

 [[ 51 102  94]
  [ 50 101  93]
  [ 49 102  94]
  ...
  [ 92  88  91]
  [ 95  91  94]
  [ 95  91  94]]

 [[ 52 103  95]
  [ 51 102  94]
  [ 50 103  95]
  ...
  [ 91  87  90]
  [ 93  89  92]
  [ 93  89  92]]

 [[ 52 103  95]
  [ 51 102  94]
  [ 50 103  95]
  ...
  [ 91  87  90]
  [ 93  89  92]
  [ 93  89  92]]]
(320, 320)
[[[ 61 123 115]
  [ 62 124 116]
  [ 61 125 117]
  ...
  [ 44  74  79]
  [ 44  74  79]
  [ 44  74  79]]

 [[ 61 123 115]
  [ 61 123 115]
  [ 60 124 116]
  ...
  [ 40  70  75]
  [ 40  70  75]
  [ 40  70  75]]

 [[ 62 124 116]
  [ 62 124 116]
  [ 62 124 116]
  ...
  [ 49  80  82]
  [ 49  80  82]
  [ 49  80  82]]

 ...

 [[ 50 102  96]
  [ 51 103  97

[[[136 136 136]
  [136 136 136]
  [133 133 133]
  ...
  [  0  54  41]
  [ 14  68  55]
  [ 13  67  54]]

 [[118 118 118]
  [118 118 118]
  [117 117 117]
  ...
  [  8  62  49]
  [ 33  87  74]
  [ 36  90  77]]

 [[105 105 105]
  [105 105 105]
  [108 108 108]
  ...
  [ 20  74  61]
  [ 35  89  76]
  [ 35  89  76]]

 ...

 [[121  92 154]
  [131 102 164]
  [155 129 184]
  ...
  [ 55 138 127]
  [ 59 142 131]
  [ 61 144 133]]

 [[125  91 158]
  [135 101 168]
  [159 126 188]
  ...
  [ 51 134 123]
  [ 55 138 127]
  [ 58 141 130]]

 [[152 118 185]
  [155 121 188]
  [162 129 191]
  ...
  [ 50 133 122]
  [ 53 136 125]
  [ 55 138 127]]]
(320, 320)
[[[108 108 108]
  [108 108 108]
  [109 109 109]
  ...
  [ 13  72  58]
  [ 26  85  71]
  [ 37  96  82]]

 [[111 111 111]
  [111 111 111]
  [112 112 112]
  ...
  [  0  57  43]
  [ 11  70  56]
  [ 22  81  67]]

 [[118 118 118]
  [118 118 118]
  [119 119 119]
  ...
  [  0  46  32]
  [  0  58  44]
  [ 10  69  55]]

 ...

 [[114 100 119]
  [101  87 106]
  [ 99  8

[[[ 18  28  25]
  [ 20  30  27]
  [ 20  32  29]
  ...
  [ 22  48  46]
  [ 24  48  45]
  [ 25  49  46]]

 [[ 16  26  23]
  [ 17  27  24]
  [ 18  30  27]
  ...
  [ 23  49  47]
  [ 26  50  47]
  [ 27  51  48]]

 [[ 11  21  18]
  [ 13  23  20]
  [ 13  25  22]
  ...
  [ 26  49  48]
  [ 27  50  49]
  [ 27  50  49]]

 ...

 [[103 113 130]
  [104 114 131]
  [107 117 134]
  ...
  [250 250 255]
  [246 244 255]
  [241 239 253]]

 [[104 114 131]
  [106 116 133]
  [108 118 135]
  ...
  [245 245 255]
  [244 243 255]
  [244 243 255]]

 [[104 114 131]
  [106 116 133]
  [108 118 135]
  ...
  [134 134 148]
  [138 137 154]
  [145 144 161]]]
(320, 320)
[[[ 48  68  63]
  [ 44  64  59]
  [ 37  57  52]
  ...
  [ 27  94  90]
  [ 28  93  88]
  [ 25  90  85]]

 [[ 50  70  65]
  [ 48  68  63]
  [ 44  64  59]
  ...
  [ 27  94  90]
  [ 28  93  88]
  [ 25  90  85]]

 [[ 37  57  52]
  [ 40  60  55]
  [ 41  61  56]
  ...
  [ 24  91  87]
  [ 26  91  86]
  [ 24  89  84]]

 ...

 [[114 126 145]
  [114 126 145]
  [115 12

[[[ 50  40  35]
  [ 50  40  35]
  [ 49  39  34]
  ...
  [ 15  17  19]
  [ 17  19  21]
  [ 20  22  24]]

 [[ 50  40  35]
  [ 50  40  35]
  [ 49  39  34]
  ...
  [ 15  17  19]
  [ 17  19  21]
  [ 20  22  24]]

 [[ 50  40  35]
  [ 50  40  35]
  [ 49  39  34]
  ...
  [ 15  17  19]
  [ 17  19  21]
  [ 20  22  24]]

 ...

 [[ 64  98 104]
  [ 57  91  97]
  [ 60  94 100]
  ...
  [ 84  84  91]
  [105 105 112]
  [123 123 130]]

 [[ 75 109 115]
  [ 60  94 100]
  [ 54  88  94]
  ...
  [ 83  85  92]
  [ 81  83  90]
  [ 86  88  95]]

 [[ 77 111 117]
  [ 67 101 107]
  [ 72 106 112]
  ...
  [ 93  95 102]
  [ 90  92  99]
  [ 83  85  92]]]
(320, 320)
[[[ 49  36  32]
  [ 49  36  32]
  [ 49  36  32]
  ...
  [ 11  10  12]
  [ 12  11  13]
  [ 15  14  16]]

 [[ 49  36  32]
  [ 49  36  32]
  [ 49  36  32]
  ...
  [ 11  10  12]
  [ 12  11  13]
  [ 15  14  16]]

 [[ 49  36  32]
  [ 49  36  32]
  [ 48  35  31]
  ...
  [ 11  10  12]
  [ 12  11  13]
  [ 15  14  16]]

 ...

 [[ 56  92  93]
  [ 56  92  93]
  [ 58  9

[[[ 27  23  19]
  [ 27  23  19]
  [ 29  22  19]
  ...
  [ 34  46  45]
  [ 34  46  45]
  [ 36  48  47]]

 [[ 27  23  19]
  [ 28  24  20]
  [ 30  23  20]
  ...
  [ 32  44  43]
  [ 33  45  44]
  [ 36  48  47]]

 [[ 29  22  19]
  [ 30  23  20]
  [ 30  23  20]
  ...
  [ 32  42  41]
  [ 32  42  41]
  [ 35  45  44]]

 ...

 [[120 127 140]
  [118 125 138]
  [117 124 137]
  ...
  [120 111 115]
  [121 112 116]
  [122 113 117]]

 [[135 142 155]
  [133 140 153]
  [131 138 151]
  ...
  [118 112 115]
  [120 111 115]
  [121 112 116]]

 [[118 125 138]
  [117 124 137]
  [118 125 138]
  ...
  [118 112 115]
  [120 111 115]
  [120 111 115]]]
(320, 320)
[[[ 30  23  20]
  [ 30  23  20]
  [ 32  23  20]
  ...
  [ 32  42  39]
  [ 32  42  41]
  [ 32  42  41]]

 [[ 30  23  20]
  [ 30  23  20]
  [ 32  23  20]
  ...
  [ 32  42  39]
  [ 34  44  43]
  [ 35  45  44]]

 [[ 29  22  19]
  [ 30  23  20]
  [ 30  23  20]
  ...
  [ 35  45  42]
  [ 37  47  46]
  [ 38  48  47]]

 ...

 [[114 119 132]
  [113 118 131]
  [110 11

  [128 126 131]]]
(320, 320)
[[[ 33  24  21]
  [ 33  24  21]
  [ 33  24  21]
  ...
  [ 40  32  27]
  [ 42  34  29]
  [ 42  34  29]]

 [[ 32  23  20]
  [ 32  23  20]
  [ 32  23  20]
  ...
  [ 42  34  29]
  [ 42  34  29]
  [ 42  34  29]]

 [[ 32  23  20]
  [ 32  23  20]
  [ 32  23  20]
  ...
  [ 42  34  29]
  [ 42  34  29]
  [ 42  34  29]]

 ...

 [[124 126 133]
  [151 153 160]
  [191 193 200]
  ...
  [128 123 129]
  [135 130 136]
  [142 137 143]]

 [[154 156 163]
  [183 185 192]
  [217 219 226]
  ...
  [118 113 119]
  [121 119 124]
  [128 126 131]]

 [[195 197 204]
  [212 214 221]
  [223 225 232]
  ...
  [118 113 119]
  [122 120 125]
  [128 126 131]]]
(320, 320)
[[[ 33  24  21]
  [ 33  24  21]
  [ 33  24  21]
  ...
  [ 42  34  29]
  [ 42  34  29]
  [ 42  34  29]]

 [[ 32  23  20]
  [ 32  23  20]
  [ 32  23  20]
  ...
  [ 42  34  29]
  [ 42  34  29]
  [ 42  34  29]]

 [[ 32  23  20]
  [ 32  23  20]
  [ 32  23  20]
  ...
  [ 42  34  29]
  [ 42  34  29]
  [ 42  34  29]]

 ...

 [[144 146 1

[[[ 34  25  22]
  [ 35  26  23]
  [ 38  29  26]
  ...
  [ 52  46  41]
  [ 60  54  49]
  [ 61  55  50]]

 [[ 34  25  22]
  [ 35  26  23]
  [ 37  28  25]
  ...
  [ 54  48  43]
  [ 63  57  52]
  [ 64  58  53]]

 [[ 34  25  22]
  [ 35  26  23]
  [ 35  26  23]
  ...
  [ 49  43  38]
  [ 57  51  46]
  [ 58  52  47]]

 ...

 [[173 174 179]
  [171 172 177]
  [182 182 189]
  ...
  [166 164 169]
  [172 170 175]
  [174 172 177]]

 [[187 188 193]
  [199 200 205]
  [217 217 224]
  ...
  [164 162 167]
  [167 165 170]
  [167 165 170]]

 [[128 129 134]
  [141 142 147]
  [160 160 167]
  ...
  [161 159 164]
  [161 159 164]
  [161 159 164]]]
(320, 320)
[[[ 34  25  22]
  [ 35  26  23]
  [ 38  29  26]
  ...
  [ 53  47  42]
  [ 61  55  50]
  [ 63  57  52]]

 [[ 34  25  22]
  [ 35  26  23]
  [ 37  28  25]
  ...
  [ 53  47  42]
  [ 61  55  50]
  [ 64  58  53]]

 [[ 34  25  22]
  [ 35  26  23]
  [ 35  26  23]
  ...
  [ 47  41  36]
  [ 56  50  45]
  [ 57  51  46]]

 ...

 [[169 172 177]
  [175 178 183]
  [180 18

[[[ 36  32  28]
  [ 35  31  27]
  [ 34  30  26]
  ...
  [ 38  53  49]
  [ 33  48  44]
  [ 27  42  38]]

 [[ 36  32  28]
  [ 34  30  26]
  [ 34  30  26]
  ...
  [ 41  56  52]
  [ 37  52  48]
  [ 30  45  41]]

 [[ 35  31  27]
  [ 36  32  28]
  [ 36  32  28]
  ...
  [ 48  60  57]
  [ 47  59  56]
  [ 39  51  48]]

 ...

 [[180 177 184]
  [158 155 162]
  [154 148 156]
  ...
  [157 154 161]
  [156 153 160]
  [154 151 158]]

 [[176 173 180]
  [157 154 161]
  [160 154 162]
  ...
  [149 146 153]
  [146 143 150]
  [146 143 150]]

 [[175 172 179]
  [157 154 161]
  [162 156 164]
  ...
  [144 141 148]
  [143 140 147]
  [143 140 147]]]
(320, 320)
[[[ 36  32  28]
  [ 34  30  26]
  [ 34  30  26]
  ...
  [ 39  54  50]
  [ 32  47  43]
  [ 27  42  38]]

 [[ 35  31  27]
  [ 35  31  27]
  [ 35  31  27]
  ...
  [ 44  59  55]
  [ 38  53  49]
  [ 32  47  43]]

 [[ 35  31  27]
  [ 36  32  28]
  [ 37  33  29]
  ...
  [ 47  59  56]
  [ 43  55  52]
  [ 39  51  48]]

 ...

 [[179 176 183]
  [157 154 161]
  [158 15

[[[ 38  31  28]
  [ 39  32  29]
  [ 38  34  30]
  ...
  [ 41  47  42]
  [ 41  47  42]
  [ 41  47  42]]

 [[ 38  31  28]
  [ 38  31  28]
  [ 36  32  28]
  ...
  [ 42  48  43]
  [ 42  48  43]
  [ 43  49  44]]

 [[ 42  35  32]
  [ 42  35  32]
  [ 40  33  30]
  ...
  [ 44  48  43]
  [ 45  49  44]
  [ 45  49  44]]

 ...

 [[151 148 149]
  [154 151 152]
  [164 158 161]
  ...
  [134 130 133]
  [139 135 138]
  [140 136 139]]

 [[151 148 149]
  [153 150 151]
  [161 155 158]
  ...
  [130 126 129]
  [139 135 138]
  [142 138 141]]

 [[151 148 149]
  [153 150 151]
  [158 152 155]
  ...
  [126 122 125]
  [137 133 136]
  [140 136 139]]]
(320, 320)
[[[ 39  32  29]
  [ 40  33  30]
  [ 38  34  30]
  ...
  [ 36  42  37]
  [ 33  39  34]
  [ 31  37  32]]

 [[ 38  31  28]
  [ 38  31  28]
  [ 36  32  28]
  ...
  [ 36  42  37]
  [ 35  41  36]
  [ 33  39  34]]

 [[ 42  35  32]
  [ 40  33  30]
  [ 37  33  29]
  ...
  [ 38  42  37]
  [ 37  41  36]
  [ 35  39  34]]

 ...

 [[153 150 151]
  [160 157 158]
  [168 16

[[[ 44  46  39]
  [ 48  50  43]
  [ 50  52  45]
  ...
  [ 44  44  42]
  [ 47  47  45]
  [ 47  47  45]]

 [[ 40  42  35]
  [ 43  45  38]
  [ 46  48  41]
  ...
  [ 46  46  44]
  [ 50  50  48]
  [ 50  50  48]]

 [[ 44  46  39]
  [ 45  47  40]
  [ 44  46  39]
  ...
  [ 47  47  45]
  [ 50  50  48]
  [ 50  50  48]]

 ...

 [[172 165 171]
  [148 141 147]
  [114 106 114]
  ...
  [133 132 134]
  [135 134 136]
  [129 128 130]]

 [[172 165 171]
  [148 141 147]
  [114 106 114]
  ...
  [130 129 131]
  [138 137 139]
  [135 134 136]]

 [[172 165 171]
  [148 141 147]
  [114 106 114]
  ...
  [149 148 150]
  [159 158 160]
  [157 156 158]]]
(320, 320)
[[[ 44  46  39]
  [ 48  50  43]
  [ 50  52  45]
  ...
  [ 46  46  44]
  [ 48  48  46]
  [ 48  48  46]]

 [[ 40  42  35]
  [ 43  45  38]
  [ 46  48  41]
  ...
  [ 48  48  46]
  [ 50  50  48]
  [ 50  50  48]]

 [[ 44  46  39]
  [ 45  47  40]
  [ 44  46  39]
  ...
  [ 50  50  48]
  [ 50  50  48]
  [ 50  50  48]]

 ...

 [[169 162 168]
  [139 132 138]
  [113 10

(320, 320)
[[[ 48  71  84]
  [ 47  70  83]
  [ 49  71  86]
  ...
  [ 43  43  55]
  [ 60  60  72]
  [ 69  69  81]]

 [[ 46  69  82]
  [ 46  69  82]
  [ 47  69  84]
  ...
  [ 57  57  69]
  [ 69  69  81]
  [ 76  76  88]]

 [[ 45  67  77]
  [ 46  68  78]
  [ 46  69  82]
  ...
  [ 61  61  73]
  [ 62  62  74]
  [ 63  63  75]]

 ...

 [[ 37  36  38]
  [ 39  38  40]
  [ 39  38  40]
  ...
  [119 115 118]
  [119 115 118]
  [119 115 118]]

 [[ 37  36  38]
  [ 39  38  40]
  [ 39  38  40]
  ...
  [119 115 118]
  [119 115 118]
  [119 115 118]]

 [[ 37  36  38]
  [ 39  38  40]
  [ 39  38  40]
  ...
  [119 115 118]
  [119 115 118]
  [119 115 118]]]
(320, 320)
[[[ 49  71  86]
  [ 57  79  94]
  [ 63  84 102]
  ...
  [ 13  13  25]
  [ 13  13  25]
  [ 13  13  25]]

 [[ 46  68  83]
  [ 53  75  90]
  [ 60  81  99]
  ...
  [ 21  21  33]
  [ 21  21  33]
  [ 21  21  33]]

 [[ 42  68  80]
  [ 46  72  84]
  [ 53  78  92]
  ...
  [ 21  22  32]
  [ 21  22  32]
  [ 21  22  32]]

 ...

 [[ 31  30  32]
  [ 44  43  45

[[[113 118 129]
  [166 171 182]
  [177 184 195]
  ...
  [108 115 135]
  [112 119 139]
  [116 123 143]]

 [[ 52  57  68]
  [ 82  87  98]
  [140 147 158]
  ...
  [111 118 138]
  [117 124 144]
  [120 127 147]]

 [[ 68  72  81]
  [ 54  58  67]
  [ 64  70  79]
  ...
  [ 85  92 112]
  [ 91  98 118]
  [ 95 102 122]]

 ...

 [[ 88  84  87]
  [ 90  86  89]
  [ 82  90  94]
  ...
  [ 78  74  77]
  [ 77  73  76]
  [ 77  73  76]]

 [[ 90  86  89]
  [ 90  86  89]
  [ 81  89  93]
  ...
  [ 80  76  79]
  [ 78  74  77]
  [ 78  74  77]]

 [[ 90  86  89]
  [ 90  86  89]
  [ 81  89  93]
  ...
  [ 80  76  79]
  [ 78  74  77]
  [ 78  74  77]]]
(320, 320)
[[[178 186 195]
  [163 171 180]
  [108 116 125]
  ...
  [ 56  63  83]
  [ 81  88 108]
  [ 85  92 112]]

 [[121 129 138]
  [169 177 186]
  [174 182 191]
  ...
  [ 65  72  92]
  [ 99 106 126]
  [102 109 129]]

 [[ 58  63  69]
  [ 91  96 102]
  [145 150 156]
  ...
  [ 89  98 118]
  [115 124 144]
  [ 96 105 125]]

 ...

 [[ 40  67  74]
  [ 44  71  78]
  [ 38  6

[[[171 176 182]
  [185 190 196]
  [128 134 143]
  ...
  [ 23  30  36]
  [ 23  30  36]
  [ 23  30  36]]

 [[ 93  98 104]
  [160 165 171]
  [186 192 201]
  ...
  [ 23  30  36]
  [ 23  30  36]
  [ 23  30  36]]

 [[ 67  69  76]
  [ 76  78  85]
  [139 144 150]
  ...
  [ 23  30  36]
  [ 23  30  36]
  [ 23  30  36]]

 ...

 [[140 147 160]
  [135 142 155]
  [142 147 160]
  ...
  [ 59  60  65]
  [ 59  60  65]
  [ 59  60  65]]

 [[143 150 161]
  [141 148 159]
  [148 153 166]
  ...
  [ 59  60  65]
  [ 59  60  65]
  [ 59  60  65]]

 [[147 154 165]
  [145 152 163]
  [151 156 169]
  ...
  [ 59  60  65]
  [ 59  60  65]
  [ 59  60  65]]]
(320, 320)
[[[182 187 193]
  [163 168 174]
  [ 95 101 110]
  ...
  [ 23  28  34]
  [ 22  27  33]
  [ 22  27  33]]

 [[117 122 128]
  [180 185 191]
  [180 186 195]
  ...
  [ 23  28  34]
  [ 22  27  33]
  [ 22  27  33]]

 [[ 55  57  64]
  [ 98 100 107]
  [171 176 182]
  ...
  [ 22  27  33]
  [ 22  27  33]
  [ 22  27  33]]

 ...

 [[158 159 169]
  [155 156 166]
  [148 14

[[[ 57  86  95]
  [ 57  86  95]
  [ 57  86  95]
  ...
  [ 43  44  49]
  [ 47  45  50]
  [ 50  48  53]]

 [[ 61  90  99]
  [ 61  90  99]
  [ 61  90  99]
  ...
  [ 41  42  47]
  [ 46  44  49]
  [ 48  46  51]]

 [[ 69  92 105]
  [ 69  92 105]
  [ 69  92 105]
  ...
  [ 41  42  47]
  [ 45  44  46]
  [ 45  44  46]]

 ...

 [[ 70  72  79]
  [ 70  72  79]
  [ 70  72  79]
  ...
  [ 82  95 103]
  [ 71  83  93]
  [ 49  61  71]]

 [[ 70  72  79]
  [ 70  72  79]
  [ 70  72  79]
  ...
  [ 54  67  75]
  [ 52  64  74]
  [ 49  61  71]]

 [[ 70  72  79]
  [ 70  72  79]
  [ 70  72  79]
  ...
  [ 43  56  64]
  [ 43  55  65]
  [ 50  62  72]]]
(320, 320)
[[[ 62  89  98]
  [ 62  89  98]
  [ 62  89  98]
  ...
  [ 41  42  47]
  [ 41  42  47]
  [ 42  43  48]]

 [[ 67  94 103]
  [ 67  94 103]
  [ 67  94 103]
  ...
  [ 41  42  47]
  [ 40  41  46]
  [ 41  42  47]]

 [[ 74  95 108]
  [ 74  95 108]
  [ 74  95 108]
  ...
  [ 42  43  48]
  [ 40  41  46]
  [ 40  41  46]]

 ...

 [[ 70  72  79]
  [ 70  72  79]
  [ 70  7

[[[30 36 52]
  [30 36 52]
  [33 39 55]
  ...
  [51 52 57]
  [49 51 53]
  [48 50 52]]

 [[28 34 50]
  [28 34 50]
  [32 38 54]
  ...
  [50 51 56]
  [49 51 53]
  [49 51 53]]

 [[33 39 55]
  [33 39 55]
  [35 41 57]
  ...
  [51 52 57]
  [49 51 53]
  [49 51 53]]

 ...

 [[78 77 79]
  [78 77 79]
  [79 78 80]
  ...
  [65 71 75]
  [63 70 76]
  [59 66 72]]

 [[78 77 79]
  [78 77 79]
  [79 78 80]
  ...
  [79 85 89]
  [76 83 89]
  [69 76 82]]

 [[78 77 79]
  [78 77 79]
  [79 78 80]
  ...
  [79 85 89]
  [69 76 82]
  [59 66 72]]]
(320, 320)
[[[ 35  40  53]
  [ 35  40  53]
  [ 35  40  53]
  ...
  [ 57  61  63]
  [ 55  58  63]
  [ 53  56  61]]

 [[ 35  40  53]
  [ 35  40  53]
  [ 35  40  53]
  ...
  [ 41  45  47]
  [ 32  35  40]
  [ 35  38  43]]

 [[ 35  40  53]
  [ 35  40  53]
  [ 35  40  53]
  ...
  [130 134 136]
  [ 80  83  88]
  [ 56  59  64]]

 ...

 [[ 73  71  76]
  [ 73  71  76]
  [ 69  67  72]
  ...
  [ 48  60  65]
  [ 48  60  65]
  [ 48  60  65]]

 [[ 68  66  71]
  [ 67  65  70]
  [ 65  63  6

[[[ 8 26 19]
  [ 8 26 19]
  [ 9 27 20]
  ...
  [19 35 35]
  [21 38 36]
  [21 38 36]]

 [[ 8 26 19]
  [ 8 26 19]
  [ 9 27 20]
  ...
  [19 35 35]
  [21 38 36]
  [21 38 36]]

 [[10 28 21]
  [10 28 21]
  [11 29 22]
  ...
  [18 34 34]
  [23 38 36]
  [23 38 36]]

 ...

 [[38 43 49]
  [38 43 49]
  [39 44 50]
  ...
  [62 65 70]
  [63 65 67]
  [63 65 67]]

 [[37 42 48]
  [37 42 48]
  [38 43 49]
  ...
  [68 71 76]
  [70 72 74]
  [70 72 74]]

 [[37 42 48]
  [37 42 48]
  [38 43 49]
  ...
  [68 71 76]
  [73 75 77]
  [73 75 77]]]
(320, 320)
[[[ 12  24  21]
  [ 11  23  20]
  [ 11  23  20]
  ...
  [ 18  35  33]
  [ 17  34  32]
  [ 15  32  30]]

 [[ 12  24  21]
  [ 11  23  20]
  [ 11  23  20]
  ...
  [ 18  35  33]
  [ 17  34  32]
  [ 15  32  30]]

 [[ 12  24  21]
  [ 11  23  20]
  [ 11  23  20]
  ...
  [ 18  33  31]
  [ 18  33  31]
  [ 17  32  30]]

 ...

 [[ 47  52  58]
  [ 47  52  58]
  [ 46  51  57]
  ...
  [ 78  82  84]
  [ 75  79  81]
  [ 70  74  76]]

 [[ 50  55  61]
  [ 50  55  61]
  [ 48  53  5

[[[ 24  32  31]
  [ 24  32  31]
  [ 25  33  32]
  ...
  [ 20  24  26]
  [ 19  23  25]
  [ 17  21  23]]

 [[ 24  32  31]
  [ 24  32  31]
  [ 25  33  32]
  ...
  [ 20  24  26]
  [ 19  23  25]
  [ 17  21  23]]

 [[ 24  32  31]
  [ 24  32  31]
  [ 25  33  32]
  ...
  [ 20  24  26]
  [ 19  23  25]
  [ 17  21  23]]

 ...

 [[ 53  98 107]
  [ 53  98 107]
  [ 53  98 107]
  ...
  [ 45  47  54]
  [ 43  44  54]
  [ 43  44  54]]

 [[ 52  96 107]
  [ 52  96 107]
  [ 52  96 107]
  ...
  [ 45  47  54]
  [ 43  45  52]
  [ 42  44  51]]

 [[ 50  94 105]
  [ 50  94 105]
  [ 50  94 105]
  ...
  [ 45  47  54]
  [ 45  47  54]
  [ 45  47  54]]]
(320, 320)
[[[ 26  33  34]
  [ 26  33  34]
  [ 27  31  33]
  ...
  [ 92  95  95]
  [ 95  95  95]
  [ 94  94  94]]

 [[ 26  33  34]
  [ 26  33  34]
  [ 27  31  33]
  ...
  [ 92  95  95]
  [ 95  95  95]
  [ 94  94  94]]

 [[ 26  33  34]
  [ 26  33  34]
  [ 27  31  33]
  ...
  [ 92  95  95]
  [ 95  95  95]
  [ 95  95  95]]

 ...

 [[ 59 106 115]
  [ 59 106 115]
  [ 58 10

[[[ 47  77  77]
  [ 47  77  77]
  [ 51  76  77]
  ...
  [ 23  24  29]
  [ 24  27  32]
  [ 24  27  32]]

 [[ 67  97  97]
  [ 67  97  97]
  [ 71  96  97]
  ...
  [ 23  24  29]
  [ 24  27  32]
  [ 24  27  32]]

 [[ 62  98  99]
  [ 62  98  99]
  [ 61  97  98]
  ...
  [ 23  24  29]
  [ 24  27  32]
  [ 24  27  32]]

 ...

 [[132 134 141]
  [134 136 143]
  [146 148 155]
  ...
  [ 53  51  56]
  [ 53  51  56]
  [ 55  53  58]]

 [[116 118 125]
  [118 120 127]
  [131 133 140]
  ...
  [ 48  46  51]
  [ 50  48  53]
  [ 50  48  53]]

 [[103 105 112]
  [105 107 114]
  [119 121 128]
  ...
  [ 47  45  50]
  [ 47  45  50]
  [ 47  45  50]]]
(320, 320)
[[[ 60  93  95]
  [ 60  93  95]
  [ 62  91  93]
  ...
  [ 20  21  26]
  [ 19  20  25]
  [ 17  18  23]]

 [[ 67 100 102]
  [ 67 100 102]
  [ 69  98 100]
  ...
  [ 20  21  26]
  [ 19  20  25]
  [ 17  18  23]]

 [[ 56  91  95]
  [ 56  91  95]
  [ 56  91  95]
  ...
  [ 20  21  26]
  [ 19  20  25]
  [ 17  18  23]]

 ...

 [[149 155 159]
  [145 151 155]
  [139 14

[[[ 26  29  29]
  [ 26  29  29]
  [ 27  30  30]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 [[ 29  32  32]
  [ 29  32  32]
  [ 30  33  33]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 [[ 36  39  39]
  [ 36  39  39]
  [ 36  39  39]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 ...

 [[ 73  76  81]
  [ 76  79  84]
  [ 84  87  92]
  ...
  [ 85  83  88]
  [ 91  89  94]
  [ 96  94  99]]

 [[111 114 119]
  [114 117 122]
  [123 126 131]
  ...
  [ 91  89  94]
  [ 93  91  96]
  [ 94  92  97]]

 [[114 117 122]
  [111 114 119]
  [103 106 111]
  ...
  [ 91  89  94]
  [ 91  89  94]
  [ 89  87  92]]]
(320, 320)
[[[ 26  29  29]
  [ 26  29  29]
  [ 26  29  29]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 [[ 26  29  29]
  [ 26  29  29]
  [ 26  29  29]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 [[ 29  32  32]
  [ 29  32  32]
  [ 29  32  32]
  ...
  [ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]]

 ...

 [[117 120 125]
  [112 115 120]
  [ 97 10

[[[ 42  45  43]
  [ 41  44  42]
  [ 40  43  41]
  ...
  [ 31  31  38]
  [ 31  31  38]
  [ 31  31  38]]

 [[ 42  45  43]
  [ 41  44  42]
  [ 40  43  41]
  ...
  [ 31  31  38]
  [ 31  31  38]
  [ 31  31  38]]

 [[ 42  45  43]
  [ 42  45  43]
  [ 40  43  41]
  ...
  [ 31  31  38]
  [ 31  31  38]
  [ 31  31  38]]

 ...

 [[108 109 114]
  [108 109 114]
  [107 108 113]
  ...
  [123 121 126]
  [122 120 125]
  [122 120 125]]

 [[ 94  95 100]
  [ 92  93  98]
  [ 87  88  93]
  ...
  [128 126 131]
  [128 126 131]
  [128 126 131]]

 [[ 95  96 101]
  [ 93  94  99]
  [ 87  88  93]
  ...
  [131 129 134]
  [131 129 134]
  [131 129 134]]]
(320, 320)
[[[ 37  47  39]
  [ 43  53  45]
  [ 48  55  48]
  ...
  [ 34  34  41]
  [ 35  35  42]
  [ 35  35  42]]

 [[ 37  47  39]
  [ 43  53  45]
  [ 48  55  48]
  ...
  [ 33  33  40]
  [ 34  34  41]
  [ 34  34  41]]

 [[ 37  47  39]
  [ 43  53  45]
  [ 49  56  49]
  ...
  [ 30  30  37]
  [ 29  29  36]
  [ 29  29  36]]

 ...

 [[102 103 108]
  [105 106 111]
  [104 10

(320, 320)
[[[ 34  31  32]
  [ 34  31  32]
  [ 26  22  25]
  ...
  [ 43  42  44]
  [ 43  42  44]
  [ 43  42  44]]

 [[ 34  31  32]
  [ 33  30  31]
  [ 26  22  25]
  ...
  [ 43  42  44]
  [ 43  42  44]
  [ 43  42  44]]

 [[ 34  31  32]
  [ 33  30  31]
  [ 26  22  25]
  ...
  [ 43  42  44]
  [ 43  42  44]
  [ 43  42  44]]

 ...

 [[102  99 106]
  [100  97 104]
  [ 97  94 101]
  ...
  [ 83  82  84]
  [ 85  84  86]
  [ 85  84  86]]

 [[114 111 118]
  [117 114 121]
  [118 115 122]
  ...
  [ 85  84  86]
  [ 85  84  86]
  [ 85  84  86]]

 [[123 120 127]
  [125 122 129]
  [125 122 129]
  ...
  [ 86  85  87]
  [ 86  85  87]
  [ 86  85  87]]]
(320, 320)
[[[ 34  30  33]
  [ 26  22  25]
  [ 75  69  72]
  ...
  [ 41  40  42]
  [ 40  39  41]
  [ 40  39  41]]

 [[ 34  30  33]
  [ 26  22  25]
  [ 75  69  72]
  ...
  [ 41  40  42]
  [ 40  39  41]
  [ 40  39  41]]

 [[ 33  29  32]
  [ 26  22  25]
  [ 76  70  73]
  ...
  [ 41  40  42]
  [ 40  39  41]
  [ 40  39  41]]

 ...

 [[101  99 104]
  [ 98  96 101

[[[ 61  61  61]
  [ 61  61  61]
  [ 62  62  62]
  ...
  [ 12  17  17]
  [ 13  18  18]
  [ 13  18  18]]

 [[ 61  61  61]
  [ 61  61  61]
  [ 62  62  62]
  ...
  [ 12  17  17]
  [ 13  18  18]
  [ 13  18  18]]

 [[ 61  61  61]
  [ 61  61  61]
  [ 62  62  62]
  ...
  [ 12  17  17]
  [ 13  18  18]
  [ 13  18  18]]

 ...

 [[154 149 155]
  [154 149 155]
  [155 150 156]
  ...
  [ 41  48  61]
  [ 40  47  60]
  [ 40  47  60]]

 [[154 149 155]
  [154 149 155]
  [155 150 156]
  ...
  [ 40  47  60]
  [ 39  46  59]
  [ 39  46  59]]

 [[154 149 155]
  [154 149 155]
  [155 150 156]
  ...
  [ 40  47  60]
  [ 39  46  59]
  [ 39  46  59]]]
(320, 320)
[[[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ...
  [  9  11  13]
  [  9  11  13]
  [  9  11  13]]

 [[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ...
  [  9  11  13]
  [  9  11  13]
  [  9  11  13]]

 [[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ...
  [  9  11  13]
  [  9  11  13]
  [  9  11  13]]

 ...

 [[ 67  63  66]
  [ 66  62  65]
  [ 61  6

(320, 320)
[[[ 52  55  53]
  [ 52  55  53]
  [ 54  54  52]
  ...
  [ 41  44  44]
  [ 41  44  44]
  [ 41  44  44]]

 [[ 52  55  53]
  [ 52  55  53]
  [ 54  54  52]
  ...
  [ 42  45  45]
  [ 42  45  45]
  [ 42  45  45]]

 [[ 55  55  55]
  [ 54  54  54]
  [ 54  54  54]
  ...
  [ 43  46  46]
  [ 43  46  46]
  [ 43  46  46]]

 ...

 [[ 34  40  49]
  [ 34  40  49]
  [ 34  40  49]
  ...
  [179 180 185]
  [179 180 185]
  [179 180 185]]

 [[ 34  40  49]
  [ 34  40  49]
  [ 34  40  49]
  ...
  [179 180 185]
  [179 180 185]
  [179 180 185]]

 [[ 34  40  49]
  [ 34  40  49]
  [ 34  40  49]
  ...
  [179 180 185]
  [179 180 185]
  [179 180 185]]]
(320, 320)
[[[ 51  54  52]
  [ 50  53  51]
  [ 50  53  51]
  ...
  [ 55  55  62]
  [ 52  53  58]
  [ 51  52  57]]

 [[ 50  53  51]
  [ 50  53  51]
  [ 50  53  51]
  ...
  [ 55  55  62]
  [ 52  53  58]
  [ 50  51  56]]

 [[ 50  53  51]
  [ 49  52  50]
  [ 49  52  50]
  ...
  [ 54  53  63]
  [ 54  54  61]
  [ 52  52  59]]

 ...

 [[ 34  40  49]
  [ 34  40  49

[[[ 42  39  40]
  [ 42  39  40]
  [ 41  38  39]
  ...
  [113 106 103]
  [113 106 103]
  [113 106 103]]

 [[ 43  40  41]
  [ 43  40  41]
  [ 42  39  40]
  ...
  [109 102  99]
  [109 102  99]
  [109 102  99]]

 [[ 46  42  45]
  [ 45  41  44]
  [ 41  40  42]
  ...
  [105 101  97]
  [105 101  97]
  [105 101  97]]

 ...

 [[ 36  48  58]
  [ 36  48  58]
  [ 37  49  59]
  ...
  [139 137 151]
  [134 133 150]
  [134 133 150]]

 [[ 36  48  58]
  [ 36  48  58]
  [ 37  49  59]
  ...
  [139 137 151]
  [134 133 150]
  [134 133 150]]

 [[ 36  48  58]
  [ 36  48  58]
  [ 37  49  59]
  ...
  [139 137 151]
  [134 133 150]
  [134 133 150]]]
(320, 320)
[[[ 47  43  46]
  [ 47  43  46]
  [ 44  43  45]
  ...
  [100  97 104]
  [116 113 120]
  [137 134 141]]

 [[ 49  45  48]
  [ 49  45  48]
  [ 46  45  47]
  ...
  [100  97 104]
  [116 113 120]
  [137 134 141]]

 [[ 51  50  52]
  [ 50  49  51]
  [ 45  46  51]
  ...
  [100  97 104]
  [116 113 120]
  [137 134 141]]

 ...

 [[ 31  43  53]
  [ 31  43  53]
  [ 31  4

[[[ 35  41  50]
  [ 35  41  50]
  [ 35  41  50]
  ...
  [ 27  24  25]
  [ 27  24  25]
  [ 27  24  25]]

 [[ 35  41  50]
  [ 36  42  51]
  [ 36  42  51]
  ...
  [ 29  26  27]
  [ 29  26  27]
  [ 29  26  27]]

 [[ 35  41  50]
  [ 35  41  50]
  [ 36  42  51]
  ...
  [ 37  25  27]
  [ 39  26  30]
  [ 39  26  30]]

 ...

 [[ 28  26  45]
  [ 24  22  41]
  [ 28  26  45]
  ...
  [130 126 129]
  [133 129 132]
  [135 131 134]]

 [[ 32  30  49]
  [ 27  25  44]
  [ 32  30  49]
  ...
  [133 129 132]
  [138 134 137]
  [140 136 139]]

 [[ 34  32  51]
  [ 29  27  46]
  [ 34  32  51]
  ...
  [135 131 134]
  [140 136 139]
  [141 137 140]]]
(320, 320)
[[[ 36  42  51]
  [ 36  42  51]
  [ 36  42  51]
  ...
  [ 27  24  25]
  [ 34  30  33]
  [ 39  35  38]]

 [[ 36  42  51]
  [ 36  42  51]
  [ 36  42  51]
  ...
  [ 26  23  24]
  [ 31  27  30]
  [ 35  31  34]]

 [[ 38  42  51]
  [ 38  42  51]
  [ 36  42  51]
  ...
  [ 45  34  38]
  [ 56  44  51]
  [ 60  48  55]]

 ...

 [[ 30  31  49]
  [ 25  26  44]
  [ 31  3

[[[128 124 127]
  [127 123 126]
  [129 122 128]
  ...
  [ 49  49  56]
  [ 54  54  61]
  [ 56  56  63]]

 [[128 124 127]
  [127 123 126]
  [129 122 128]
  ...
  [ 49  49  56]
  [ 54  54  61]
  [ 56  56  63]]

 [[128 124 127]
  [127 123 126]
  [127 122 128]
  ...
  [ 49  49  56]
  [ 55  55  62]
  [ 57  57  64]]

 ...

 [[ 29  33  42]
  [ 29  33  42]
  [ 25  29  38]
  ...
  [117 113 116]
  [117 113 116]
  [117 113 116]]

 [[ 24  28  37]
  [ 26  30  39]
  [ 27  31  40]
  ...
  [117 113 116]
  [117 113 116]
  [117 113 116]]

 [[ 22  26  35]
  [ 25  29  38]
  [ 30  34  43]
  ...
  [117 113 116]
  [117 113 116]
  [117 113 116]]]
(320, 320)
[[[126 122 125]
  [125 121 124]
  [127 120 126]
  ...
  [ 47  47  54]
  [ 47  47  54]
  [ 42  42  49]]

 [[126 122 125]
  [125 121 124]
  [127 120 126]
  ...
  [ 49  49  56]
  [ 49  49  56]
  [ 44  44  51]]

 [[126 122 125]
  [125 121 124]
  [125 120 126]
  ...
  [ 44  44  51]
  [ 45  45  52]
  [ 40  40  47]]

 ...

 [[ 25  29  38]
  [ 22  26  35]
  [ 24  2

[[[130 126 129]
  [130 126 129]
  [130 126 129]
  ...
  [ 48  50  52]
  [ 48  50  52]
  [ 48  50  52]]

 [[130 126 129]
  [130 126 129]
  [130 126 129]
  ...
  [ 48  50  52]
  [ 48  50  52]
  [ 48  50  52]]

 [[130 126 129]
  [130 126 129]
  [130 126 129]
  ...
  [ 47  49  51]
  [ 47  49  51]
  [ 47  49  51]]

 ...

 [[ 20  27  33]
  [ 21  28  34]
  [ 22  28  37]
  ...
  [112 108 111]
  [111 107 110]
  [111 107 110]]

 [[ 21  28  34]
  [ 22  29  35]
  [ 23  29  38]
  ...
  [112 108 111]
  [112 108 111]
  [112 108 111]]

 [[ 21  28  34]
  [ 22  29  35]
  [ 23  29  38]
  ...
  [112 108 111]
  [112 108 111]
  [112 108 111]]]
(320, 320)
[[[130 126 129]
  [130 126 129]
  [130 126 129]
  ...
  [ 48  50  52]
  [ 48  50  52]
  [ 48  50  52]]

 [[130 126 129]
  [130 126 129]
  [130 126 129]
  ...
  [ 48  50  52]
  [ 48  50  52]
  [ 48  50  52]]

 [[130 126 129]
  [130 126 129]
  [130 126 129]
  ...
  [ 45  47  49]
  [ 45  47  49]
  [ 45  47  49]]

 ...

 [[ 22  29  35]
  [ 23  30  36]
  [ 25  3

[[[135 129 132]
  [133 127 130]
  [133 128 129]
  ...
  [ 42  44  51]
  [ 42  44  51]
  [ 42  44  51]]

 [[136 130 133]
  [133 127 130]
  [133 128 129]
  ...
  [ 42  44  51]
  [ 42  44  51]
  [ 42  44  51]]

 [[136 131 132]
  [134 129 130]
  [134 129 130]
  ...
  [ 42  44  51]
  [ 42  44  51]
  [ 42  44  51]]

 ...

 [[ 25  32  43]
  [ 25  32  43]
  [ 23  30  41]
  ...
  [104 102 107]
  [107 105 110]
  [107 105 110]]

 [[ 25  32  43]
  [ 25  32  43]
  [ 26  33  44]
  ...
  [104 102 107]
  [105 103 108]
  [105 103 108]]

 [[ 25  32  43]
  [ 25  32  43]
  [ 25  32  43]
  ...
  [104 102 107]
  [105 103 108]
  [105 103 108]]]
(320, 320)
[[[133 128 129]
  [133 128 129]
  [132 126 129]
  ...
  [ 42  44  51]
  [ 42  44  51]
  [ 42  44  51]]

 [[133 128 129]
  [133 128 129]
  [133 127 130]
  ...
  [ 42  44  51]
  [ 42  44  51]
  [ 42  44  51]]

 [[135 130 131]
  [135 130 131]
  [131 127 130]
  ...
  [ 41  47  51]
  [ 41  47  51]
  [ 41  47  51]]

 ...

 [[ 25  32  43]
  [ 25  32  43]
  [ 26  3

[[[137 131 134]
  [137 131 134]
  [137 131 134]
  ...
  [ 20  25  36]
  [ 20  25  36]
  [ 20  25  36]]

 [[137 131 134]
  [137 131 134]
  [137 131 134]
  ...
  [ 22  27  38]
  [ 22  27  38]
  [ 22  27  38]]

 [[137 131 134]
  [137 131 134]
  [137 131 134]
  ...
  [ 27  32  45]
  [ 27  32  45]
  [ 27  32  45]]

 ...

 [[ 31  43  53]
  [ 26  38  48]
  [ 23  35  47]
  ...
  [ 81  92 107]
  [ 73  84  99]
  [ 71  82  97]]

 [[ 31  43  53]
  [ 26  38  48]
  [ 23  35  47]
  ...
  [ 92 103 118]
  [ 95 106 121]
  [ 95 106 121]]

 [[ 31  43  53]
  [ 26  38  48]
  [ 23  35  47]
  ...
  [ 73  84  99]
  [ 82  93 108]
  [ 85  96 111]]]
(320, 320)
[[[137 131 134]
  [137 131 134]
  [135 131 134]
  ...
  [ 22  27  40]
  [ 21  26  39]
  [ 21  26  39]]

 [[137 131 134]
  [137 131 134]
  [135 131 134]
  ...
  [ 27  32  45]
  [ 25  30  43]
  [ 25  30  43]]

 [[137 131 134]
  [137 131 134]
  [134 130 133]
  ...
  [ 29  34  47]
  [ 28  33  46]
  [ 28  33  46]]

 ...

 [[ 24  36  48]
  [ 24  36  48]
  [ 28  4

(320, 320)
[[[129 127 132]
  [128 126 131]
  [128 126 131]
  ...
  [ 52  55  55]
  [ 52  55  55]
  [ 52  55  55]]

 [[129 127 132]
  [128 126 131]
  [128 126 131]
  ...
  [ 52  55  55]
  [ 52  55  55]
  [ 52  55  55]]

 [[129 127 132]
  [129 127 132]
  [126 127 132]
  ...
  [ 49  52  52]
  [ 50  53  53]
  [ 50  53  53]]

 ...

 [[ 29  36  49]
  [ 26  33  46]
  [ 26  33  46]
  ...
  [ 66  60  63]
  [ 66  60  63]
  [ 66  60  63]]

 [[ 29  36  49]
  [ 26  33  46]
  [ 26  33  46]
  ...
  [ 65  59  62]
  [ 65  59  62]
  [ 65  59  62]]

 [[ 29  36  49]
  [ 26  33  46]
  [ 26  33  46]
  ...
  [ 65  59  62]
  [ 65  59  62]
  [ 65  59  62]]]
(320, 320)
[[[125 126 131]
  [126 127 132]
  [128 129 134]
  ...
  [ 52  55  55]
  [ 52  55  55]
  [ 52  55  55]]

 [[126 127 132]
  [126 127 132]
  [128 129 134]
  ...
  [ 51  54  54]
  [ 51  54  54]
  [ 51  54  54]]

 [[126 128 130]
  [125 127 129]
  [126 127 132]
  ...
  [ 48  51  51]
  [ 48  51  51]
  [ 48  51  51]]

 ...

 [[ 26  33  46]
  [ 26  33  46

[[[152 151 153]
  [152 151 153]
  [150 149 151]
  ...
  [ 42  59  70]
  [ 42  59  70]
  [ 42  59  70]]

 [[152 151 153]
  [152 151 153]
  [152 151 153]
  ...
  [ 42  59  70]
  [ 42  59  70]
  [ 42  59  70]]

 [[153 152 154]
  [153 152 154]
  [152 151 153]
  ...
  [ 41  58  67]
  [ 41  58  67]
  [ 41  58  67]]

 ...

 [[ 25  30  48]
  [ 26  31  49]
  [ 27  32  50]
  ...
  [ 35  77  87]
  [ 33  75  85]
  [ 33  75  85]]

 [[ 26  31  49]
  [ 27  32  50]
  [ 28  33  51]
  ...
  [ 37  79  89]
  [ 37  79  89]
  [ 37  79  89]]

 [[ 26  31  49]
  [ 26  31  49]
  [ 28  33  51]
  ...
  [ 35  77  87]
  [ 35  77  87]
  [ 34  76  86]]]
(320, 320)
[[[152 151 153]
  [151 150 152]
  [149 148 150]
  ...
  [ 41  58  69]
  [ 35  52  63]
  [ 33  50  61]]

 [[152 151 153]
  [152 151 153]
  [151 150 152]
  ...
  [ 41  58  69]
  [ 35  52  63]
  [ 33  50  61]]

 [[154 153 155]
  [152 151 153]
  [151 150 152]
  ...
  [ 40  57  66]
  [ 35  52  61]
  [ 33  50  59]]

 ...

 [[ 27  32  50]
  [ 27  32  50]
  [ 28  3

[[[129 136 149]
  [133 140 153]
  [145 152 165]
  ...
  [ 45  43  48]
  [ 46  44  49]
  [ 46  44  49]]

 [[129 136 149]
  [133 140 153]
  [145 152 165]
  ...
  [ 46  44  49]
  [ 46  44  49]
  [ 46  44  49]]

 [[137 142 155]
  [135 140 153]
  [140 145 158]
  ...
  [ 44  43  45]
  [ 44  43  45]
  [ 44  43  45]]

 ...

 [[ 22  39  50]
  [ 20  37  48]
  [ 22  38  52]
  ...
  [ 68  64  67]
  [ 68  64  67]
  [ 68  64  67]]

 [[ 21  38  49]
  [ 18  35  46]
  [ 20  36  50]
  ...
  [ 68  64  67]
  [ 68  64  67]
  [ 68  64  67]]

 [[ 21  38  49]
  [ 18  35  46]
  [ 20  36  50]
  ...
  [ 68  64  67]
  [ 68  64  67]
  [ 68  64  67]]]
(320, 320)
[[[123 133 145]
  [120 130 142]
  [126 133 146]
  ...
  [ 43  44  49]
  [ 43  44  49]
  [ 43  44  49]]

 [[136 146 158]
  [127 137 149]
  [120 127 140]
  ...
  [ 43  44  49]
  [ 43  44  49]
  [ 43  44  49]]

 [[142 149 162]
  [143 150 163]
  [132 139 150]
  ...
  [ 42  44  46]
  [ 42  44  46]
  [ 42  44  46]]

 ...

 [[ 21  38  49]
  [ 22  39  50]
  [ 25  4

[[[ 59  70  85]
  [ 51  62  77]
  [ 54  69  78]
  ...
  [ 82  92 109]
  [ 89  99 116]
  [ 93 103 120]]

 [[ 59  70  85]
  [ 51  62  77]
  [ 54  69  78]
  ...
  [ 81  91 108]
  [ 85  95 112]
  [ 87  97 114]]

 [[ 59  70  85]
  [ 51  62  77]
  [ 54  69  78]
  ...
  [ 73  83 100]
  [ 70  80  97]
  [ 67  77  94]]

 ...

 [[ 45  54  48]
  [ 47  56  50]
  [ 52  60  57]
  ...
  [ 83  82  84]
  [ 80  79  81]
  [ 73  72  74]]

 [[ 61  70  64]
  [ 65  74  68]
  [ 68  76  73]
  ...
  [ 85  84  86]
  [ 80  79  81]
  [ 72  71  73]]

 [[ 69  78  72]
  [ 73  82  76]
  [ 76  84  81]
  ...
  [ 85  84  86]
  [ 80  79  81]
  [ 72  71  73]]]
(320, 320)
[[[ 58  73  84]
  [ 51  66  77]
  [ 49  67  74]
  ...
  [ 83  93 110]
  [ 75  85 102]
  [ 28  38  55]]

 [[ 58  73  84]
  [ 51  66  77]
  [ 49  67  74]
  ...
  [ 92 102 119]
  [ 73  83 100]
  [ 22  32  49]]

 [[ 58  73  84]
  [ 51  66  77]
  [ 49  67  74]
  ...
  [ 85  95 112]
  [ 75  85 102]
  [ 28  38  55]]

 ...

 [[ 44  53  47]
  [ 58  67  61]
  [ 72  8

  [ 62  63  68]]]
(320, 320)
[[[ 70  80  92]
  [ 63  73  85]
  [ 56  68  78]
  ...
  [ 68  75  86]
  [ 61  68  79]
  [ 58  65  76]]

 [[ 70  80  92]
  [ 63  73  85]
  [ 56  68  78]
  ...
  [ 67  74  85]
  [ 61  68  79]
  [ 57  64  75]]

 [[ 78  88 100]
  [ 72  82  94]
  [ 56  68  78]
  ...
  [ 58  65  76]
  [ 54  61  72]
  [ 53  60  71]]

 ...

 [[ 41  46  57]
  [ 42  47  58]
  [ 55  61  70]
  ...
  [ 58  59  64]
  [ 58  59  64]
  [ 58  59  64]]

 [[ 45  50  61]
  [ 46  51  62]
  [ 60  66  75]
  ...
  [ 61  62  67]
  [ 62  63  68]
  [ 62  63  68]]

 [[ 49  54  65]
  [ 50  55  66]
  [ 64  70  79]
  ...
  [ 62  63  68]
  [ 62  63  68]
  [ 62  63  68]]]
(320, 320)
[[[ 70  79  94]
  [ 63  72  87]
  [ 56  68  80]
  ...
  [ 61  68  79]
  [ 58  65  76]
  [ 58  65  76]]

 [[ 70  79  94]
  [ 63  72  87]
  [ 56  68  80]
  ...
  [ 61  68  79]
  [ 58  65  76]
  [ 58  65  76]]

 [[ 73  82  97]
  [ 66  75  90]
  [ 57  69  81]
  ...
  [ 56  63  74]
  [ 55  62  73]
  [ 55  62  73]]

 ...

 [[ 41  51  

[[[ 58  80  88]
  [ 58  80  88]
  [ 59  81  89]
  ...
  [ 40  47  60]
  [ 55  62  75]
  [ 71  78  91]]

 [[ 59  81  89]
  [ 58  80  88]
  [ 59  81  89]
  ...
  [ 44  51  64]
  [ 60  67  80]
  [ 86  93 106]]

 [[ 59  76  85]
  [ 61  78  87]
  [ 61  78  87]
  ...
  [ 57  64  77]
  [ 68  75  88]
  [ 84  91 104]]

 ...

 [[ 20  30  40]
  [ 16  26  36]
  [ 14  24  34]
  ...
  [ 61  62  67]
  [ 63  64  69]
  [ 65  66  71]]

 [[ 17  27  37]
  [ 17  27  37]
  [ 19  29  39]
  ...
  [ 76  77  82]
  [ 73  74  79]
  [ 69  70  75]]

 [[ 26  36  46]
  [ 26  36  46]
  [ 30  40  50]
  ...
  [ 78  79  84]
  [ 69  70  75]
  [ 61  62  67]]]
(320, 320)
[[[ 58  80  88]
  [ 58  80  88]
  [ 58  80  88]
  ...
  [ 40  47  60]
  [ 55  62  75]
  [ 70  77  90]]

 [[ 59  81  89]
  [ 58  80  88]
  [ 58  80  88]
  ...
  [ 43  50  63]
  [ 58  65  78]
  [ 83  90 103]]

 [[ 61  78  87]
  [ 61  78  87]
  [ 60  77  86]
  ...
  [ 54  61  74]
  [ 67  74  87]
  [ 86  93 106]]

 ...

 [[ 23  33  43]
  [ 17  27  37]
  [ 14  2

[[[55 79 87]
  [55 79 87]
  [56 80 88]
  ...
  [35 42 55]
  [30 37 50]
  [47 54 67]]

 [[55 79 87]
  [55 79 87]
  [55 79 87]
  ...
  [36 43 56]
  [33 40 53]
  [48 55 68]]

 [[58 77 86]
  [58 77 86]
  [58 77 86]
  ...
  [32 39 52]
  [40 47 60]
  [57 64 77]]

 ...

 [[35 44 50]
  [29 38 44]
  [25 34 40]
  ...
  [55 56 61]
  [55 56 61]
  [59 60 65]]

 [[41 50 56]
  [35 44 50]
  [26 35 41]
  ...
  [58 59 64]
  [59 60 65]
  [63 64 69]]

 [[50 59 65]
  [43 52 58]
  [30 39 45]
  ...
  [72 73 78]
  [75 76 81]
  [73 74 79]]]
(320, 320)
[[[55 79 87]
  [55 79 87]
  [56 80 88]
  ...
  [39 46 59]
  [30 37 50]
  [43 50 63]]

 [[55 79 87]
  [55 79 87]
  [55 79 87]
  ...
  [39 46 59]
  [33 40 53]
  [44 51 64]]

 [[58 77 86]
  [58 77 86]
  [58 77 86]
  ...
  [33 40 53]
  [36 43 56]
  [54 61 74]]

 ...

 [[35 44 50]
  [29 38 44]
  [25 34 40]
  ...
  [55 56 61]
  [55 56 61]
  [59 60 65]]

 [[41 50 56]
  [35 44 50]
  [26 35 41]
  ...
  [58 59 64]
  [59 60 65]
  [63 64 69]]

 [[50 59 65]
  [43 52 58]
  [30

(320, 320)
[[[ 65  78  86]
  [ 65  78  86]
  [ 65  78  86]
  ...
  [ 32  39  52]
  [ 50  57  70]
  [ 62  69  82]]

 [[ 65  78  86]
  [ 65  78  86]
  [ 68  81  89]
  ...
  [ 29  36  49]
  [ 47  54  67]
  [ 63  70  83]]

 [[ 63  79  86]
  [ 64  80  87]
  [ 64  80  87]
  ...
  [ 29  36  49]
  [ 34  41  54]
  [ 56  63  76]]

 ...

 [[ 26  31  37]
  [ 26  31  37]
  [ 41  46  52]
  ...
  [ 61  62  67]
  [ 52  52  59]
  [ 54  54  61]]

 [[ 36  41  47]
  [ 45  50  56]
  [ 93  98 104]
  ...
  [ 62  63  68]
  [ 54  54  61]
  [ 55  55  62]]

 [[ 68  73  79]
  [ 80  85  91]
  [140 145 151]
  ...
  [ 57  58  63]
  [ 57  57  64]
  [ 57  57  64]]]
(320, 320)
[[[ 65  78  86]
  [ 65  78  86]
  [ 65  78  86]
  ...
  [ 36  43  56]
  [ 40  47  60]
  [ 50  57  70]]

 [[ 65  78  86]
  [ 65  78  86]
  [ 66  79  87]
  ...
  [ 29  36  49]
  [ 32  39  52]
  [ 55  62  75]]

 [[ 63  79  86]
  [ 64  80  87]
  [ 64  80  87]
  ...
  [ 32  39  52]
  [ 27  34  47]
  [ 44  51  64]]

 ...

 [[ 44  49  55]
  [ 43  48  54

[[[ 96 100 109]
  [ 71  75  84]
  [ 69  75  84]
  ...
  [ 47  54  67]
  [ 50  57  70]
  [ 50  57  70]]

 [[116 120 129]
  [103 107 116]
  [ 78  84  93]
  ...
  [ 44  51  64]
  [ 48  55  68]
  [ 48  55  68]]

 [[ 91  95 104]
  [107 111 120]
  [ 98 102 111]
  ...
  [ 44  51  64]
  [ 47  54  67]
  [ 47  54  67]]

 ...

 [[125 130 136]
  [139 144 150]
  [102 106 115]
  ...
  [ 54  54  61]
  [ 56  56  63]
  [ 56  56  63]]

 [[171 176 182]
  [188 193 199]
  [158 162 171]
  ...
  [ 51  51  58]
  [ 58  58  65]
  [ 61  61  68]]

 [[173 178 184]
  [158 163 169]
  [140 144 153]
  ...
  [ 52  52  59]
  [ 59  59  66]
  [ 61  61  68]]]
(320, 320)
[[[109 113 122]
  [ 86  90  99]
  [ 71  77  86]
  ...
  [ 47  54  67]
  [ 50  57  70]
  [ 50  57  70]]

 [[108 112 121]
  [111 115 124]
  [ 87  93 102]
  ...
  [ 44  51  64]
  [ 48  55  68]
  [ 48  55  68]]

 [[ 80  84  93]
  [ 95  99 108]
  [104 108 117]
  ...
  [ 44  51  64]
  [ 47  54  67]
  [ 47  54  67]]

 ...

 [[166 171 177]
  [135 140 146]
  [133 13

(320, 320)
[[[61 68 79]
  [61 68 79]
  [62 72 82]
  ...
  [50 55 68]
  [46 51 64]
  [44 49 62]]

 [[58 65 76]
  [60 67 78]
  [65 75 85]
  ...
  [48 53 66]
  [44 49 62]
  [42 47 60]]

 [[64 71 82]
  [70 77 88]
  [69 76 87]
  ...
  [46 51 64]
  [43 48 61]
  [41 46 59]]

 ...

 [[15 20 31]
  [10 15 26]
  [ 9 15 24]
  ...
  [66 64 69]
  [66 64 69]
  [66 64 69]]

 [[ 7 12 23]
  [ 6 11 22]
  [10 16 25]
  ...
  [67 65 70]
  [67 65 70]
  [67 65 70]]

 [[15 20 31]
  [14 19 30]
  [18 24 33]
  ...
  [67 65 70]
  [67 65 70]
  [67 65 70]]]
(320, 320)
[[[61 68 79]
  [62 69 80]
  [65 75 85]
  ...
  [49 54 67]
  [45 50 63]
  [44 49 62]]

 [[58 65 76]
  [62 69 80]
  [66 76 86]
  ...
  [46 51 64]
  [43 48 61]
  [42 47 60]]

 [[65 72 83]
  [71 78 89]
  [68 75 86]
  ...
  [45 50 63]
  [42 47 60]
  [41 46 59]]

 ...

 [[10 15 26]
  [ 8 13 24]
  [ 7 13 22]
  ...
  [64 62 67]
  [64 62 67]
  [64 62 67]]

 [[ 8 13 24]
  [ 9 14 25]
  [14 20 29]
  ...
  [65 63 68]
  [65 63 68]
  [65 63 68]]

 [[15 20 31]
  [16 2

(320, 320)
[[[105 103 117]
  [147 145 159]
  [160 156 175]
  ...
  [ 37  41  50]
  [ 32  36  45]
  [ 30  34  43]]

 [[108 106 120]
  [105 103 117]
  [142 138 157]
  ...
  [ 37  41  50]
  [ 31  35  44]
  [ 30  34  43]]

 [[121 119 131]
  [120 118 130]
  [118 113 127]
  ...
  [ 34  39  45]
  [ 32  37  43]
  [ 30  35  41]]

 ...

 [[113 112 122]
  [115 114 124]
  [115 112 119]
  ...
  [ 49  52  57]
  [ 48  51  56]
  [ 48  51  56]]

 [[109 108 118]
  [108 107 117]
  [101  98 105]
  ...
  [ 49  52  57]
  [ 48  51  56]
  [ 48  51  56]]

 [[ 98  97 107]
  [ 95  94 104]
  [ 83  80  87]
  ...
  [ 52  55  60]
  [ 48  51  56]
  [ 48  51  56]]]
(320, 320)
[[[125 120 132]
  [129 124 136]
  [124 119 131]
  ...
  [ 34  39  45]
  [ 32  37  43]
  [ 31  36  42]]

 [[126 121 133]
  [126 121 133]
  [128 123 135]
  ...
  [ 32  37  43]
  [ 33  38  44]
  [ 32  37  43]]

 [[123 116 127]
  [124 117 128]
  [128 121 132]
  ...
  [ 31  35  44]
  [ 36  40  49]
  [ 36  40  49]]

 ...

 [[ 78  78  85]
  [ 78  78  85

[[[36 59 65]
  [36 59 65]
  [36 59 65]
  ...
  [51 49 54]
  [52 50 55]
  [52 50 55]]

 [[37 60 66]
  [37 60 66]
  [37 60 66]
  ...
  [51 49 54]
  [51 49 54]
  [51 49 54]]

 [[39 64 70]
  [39 64 70]
  [37 62 68]
  ...
  [57 55 60]
  [55 53 58]
  [53 51 56]]

 ...

 [[69 70 75]
  [69 70 75]
  [69 70 75]
  ...
  [52 68 82]
  [51 66 77]
  [48 63 74]]

 [[71 72 77]
  [71 72 77]
  [71 72 77]
  ...
  [53 69 83]
  [52 67 78]
  [49 64 75]]

 [[73 74 79]
  [73 74 79]
  [73 74 79]
  ...
  [53 69 83]
  [52 67 78]
  [49 64 75]]]
(320, 320)
[[[36 54 68]
  [36 54 68]
  [37 55 69]
  ...
  [48 46 51]
  [50 48 53]
  [47 45 50]]

 [[38 56 70]
  [38 56 70]
  [39 57 71]
  ...
  [43 41 46]
  [41 39 44]
  [44 42 47]]

 [[38 59 72]
  [38 59 72]
  [39 60 73]
  ...
  [69 67 72]
  [51 49 54]
  [44 42 47]]

 ...

 [[68 69 74]
  [68 69 74]
  [68 69 74]
  ...
  [30 50 65]
  [27 47 62]
  [29 49 64]]

 [[70 71 76]
  [70 71 76]
  [69 70 75]
  ...
  [30 50 65]
  [27 47 62]
  [29 49 64]]

 [[72 73 78]
  [72 73 78]
  [71

[[[ 42  50  59]
  [ 42  50  59]
  [ 41  49  58]
  ...
  [162 165 165]
  [163 166 164]
  [155 158 156]]

 [[ 42  50  59]
  [ 42  50  59]
  [ 41  49  58]
  ...
  [165 168 168]
  [168 171 169]
  [158 161 159]]

 [[ 42  50  59]
  [ 42  50  59]
  [ 41  49  58]
  ...
  [173 176 176]
  [175 178 176]
  [167 170 168]]

 ...

 [[ 57  58  63]
  [ 61  62  67]
  [ 69  70  75]
  ...
  [103 106 124]
  [106 109 127]
  [110 113 131]]

 [[ 61  62  67]
  [ 69  70  75]
  [ 85  86  91]
  ...
  [107 110 128]
  [100 103 121]
  [ 99 102 120]]

 [[ 55  56  61]
  [ 64  65  70]
  [ 85  86  91]
  ...
  [ 81  84 102]
  [ 66  69  87]
  [ 63  66  84]]]
(320, 320)
[[[ 42  50  59]
  [ 42  50  59]
  [ 42  50  59]
  ...
  [162 165 163]
  [155 158 156]
  [155 158 156]]

 [[ 42  50  59]
  [ 42  50  59]
  [ 42  50  59]
  ...
  [162 165 163]
  [155 158 156]
  [155 158 156]]

 [[ 42  50  59]
  [ 42  50  59]
  [ 42  50  59]
  ...
  [165 168 166]
  [158 161 159]
  [158 161 159]]

 ...

 [[ 56  57  62]
  [ 54  55  60]
  [ 62  6

[[[ 35  43  52]
  [ 35  43  52]
  [ 35  43  52]
  ...
  [ 84 103 114]
  [ 80 103 116]
  [ 80 103 116]]

 [[ 35  43  52]
  [ 35  43  52]
  [ 35  43  52]
  ...
  [ 90 109 120]
  [ 84 107 120]
  [ 82 105 118]]

 [[ 36  44  53]
  [ 36  44  53]
  [ 36  44  53]
  ...
  [109 121 131]
  [ 98 115 126]
  [ 93 110 121]]

 ...

 [[111 109 114]
  [111 109 114]
  [112 110 115]
  ...
  [ 41  72  79]
  [ 34  68  74]
  [ 48  82  88]]

 [[115 113 118]
  [115 113 118]
  [116 114 119]
  ...
  [ 41  72  79]
  [ 34  68  74]
  [ 48  82  88]]

 [[115 113 118]
  [115 113 118]
  [116 114 119]
  ...
  [ 41  72  79]
  [ 34  68  74]
  [ 48  82  88]]]
(320, 320)
[[[ 36  44  53]
  [ 36  44  53]
  [ 36  44  53]
  ...
  [124 124 136]
  [113 118 129]
  [115 120 131]]

 [[ 35  43  52]
  [ 35  43  52]
  [ 35  43  52]
  ...
  [189 189 201]
  [174 179 190]
  [150 155 166]]

 [[ 35  43  52]
  [ 35  43  52]
  [ 35  43  52]
  ...
  [163 159 169]
  [176 175 185]
  [192 191 201]]

 ...

 [[107 108 113]
  [107 108 113]
  [107 10

[[[ 22  26  35]
  [ 15  19  28]
  [ 22  26  35]
  ...
  [  6  15  16]
  [  9  18  19]
  [ 13  22  23]]

 [[ 22  26  35]
  [ 15  19  28]
  [ 22  26  35]
  ...
  [  3  12  13]
  [  7  16  17]
  [ 11  20  21]]

 [[ 22  26  35]
  [ 15  19  28]
  [ 22  26  35]
  ...
  [  0  10  11]
  [  4  15  16]
  [  7  18  19]]

 ...

 [[ 78  83 101]
  [ 78  83 101]
  [ 80  85 103]
  ...
  [105 115 119]
  [150 160 164]
  [168 178 182]]

 [[ 77  82 100]
  [ 77  82 100]
  [ 79  84 102]
  ...
  [114 124 128]
  [149 159 163]
  [161 171 175]]

 [[ 77  82 100]
  [ 77  82 100]
  [ 79  84 102]
  ...
  [ 92 102 106]
  [127 137 141]
  [141 151 155]]]
(320, 320)
[[[ 22  27  33]
  [ 22  27  33]
  [ 22  27  33]
  ...
  [  7  18  19]
  [  9  20  21]
  [  9  20  21]]

 [[ 22  27  33]
  [ 22  27  33]
  [ 22  27  33]
  ...
  [  6  17  18]
  [  9  20  21]
  [  9  20  21]]

 [[ 22  27  33]
  [ 22  27  33]
  [ 22  27  33]
  ...
  [  6  17  18]
  [  8  19  20]
  [ 12  23  24]]

 ...

 [[ 82  92 104]
  [ 82  92 104]
  [ 83  9

[[[ 59  61  63]
  [ 59  61  63]
  [ 59  61  63]
  ...
  [ 19  23  25]
  [ 10  14  16]
  [ 14  18  20]]

 [[ 59  61  63]
  [ 59  61  63]
  [ 59  61  63]
  ...
  [ 19  23  25]
  [ 10  14  16]
  [ 14  18  20]]

 [[ 59  61  63]
  [ 59  61  63]
  [ 59  61  63]
  ...
  [ 19  23  25]
  [ 10  14  16]
  [ 14  18  20]]

 ...

 [[ 43  99 108]
  [ 43  99 108]
  [ 47  98 108]
  ...
  [ 32  38  47]
  [ 36  40  49]
  [ 37  41  50]]

 [[ 36  94 103]
  [ 36  94 103]
  [ 38  94 103]
  ...
  [ 47  51  60]
  [ 46  50  59]
  [ 47  51  60]]

 [[ 34  92 101]
  [ 34  92 101]
  [ 36  92 101]
  ...
  [ 76  80  89]
  [ 74  78  87]
  [ 72  76  85]]]
(320, 320)
[[[ 57  59  61]
  [ 57  59  61]
  [ 57  59  61]
  ...
  [ 22  25  30]
  [ 31  34  39]
  [ 29  32  37]]

 [[ 57  59  61]
  [ 57  59  61]
  [ 57  59  61]
  ...
  [ 22  25  30]
  [ 31  34  39]
  [ 29  32  37]]

 [[ 57  59  61]
  [ 57  59  61]
  [ 57  59  61]
  ...
  [ 22  25  30]
  [ 31  34  39]
  [ 29  32  37]]

 ...

 [[ 53 102 112]
  [ 53 102 112]
  [ 53 10

[[[28 25 24]
  [28 25 24]
  [28 25 24]
  ...
  [14 18 20]
  [12 16 18]
  [12 16 18]]

 [[28 25 24]
  [28 25 24]
  [28 25 24]
  ...
  [14 18 20]
  [12 16 18]
  [12 16 18]]

 [[28 25 24]
  [28 25 24]
  [28 25 24]
  ...
  [16 18 20]
  [14 16 18]
  [14 16 18]]

 ...

 [[46 75 82]
  [46 75 82]
  [49 76 83]
  ...
  [34 35 40]
  [34 35 40]
  [34 35 40]]

 [[45 76 83]
  [47 78 85]
  [50 79 86]
  ...
  [33 35 37]
  [33 35 37]
  [33 35 37]]

 [[43 74 81]
  [43 74 81]
  [45 74 81]
  ...
  [33 35 37]
  [33 35 37]
  [33 35 37]]]
(320, 320)
[[[28 25 24]
  [28 25 24]
  [28 25 24]
  ...
  [15 19 21]
  [16 18 20]
  [16 18 20]]

 [[28 25 24]
  [28 25 24]
  [28 25 24]
  ...
  [15 19 21]
  [17 19 21]
  [17 19 21]]

 [[28 25 24]
  [28 25 24]
  [28 25 24]
  ...
  [17 19 21]
  [16 17 22]
  [16 17 22]]

 ...

 [[38 72 78]
  [38 72 78]
  [38 69 76]
  ...
  [35 36 41]
  [35 36 41]
  [34 35 40]]

 [[42 71 78]
  [44 73 80]
  [43 72 79]
  ...
  [35 36 41]
  [34 35 40]
  [34 35 40]]

 [[42 71 78]
  [45 74 81]
  [45

[[[ 25  25  23]
  [ 26  26  24]
  [ 27  27  25]
  ...
  [ 13  18  18]
  [ 12  17  17]
  [ 13  18  18]]

 [[ 25  25  23]
  [ 26  26  24]
  [ 29  29  27]
  ...
  [ 13  18  18]
  [ 12  17  17]
  [ 13  18  18]]

 [[ 27  27  25]
  [ 27  27  25]
  [ 27  27  25]
  ...
  [ 12  17  17]
  [ 12  17  17]
  [ 12  17  17]]

 ...

 [[123 124 134]
  [121 122 132]
  [124 125 135]
  ...
  [ 43  41  46]
  [ 40  39  41]
  [ 40  39  41]]

 [[130 131 141]
  [126 127 137]
  [125 126 136]
  ...
  [ 43  42  44]
  [ 40  39  41]
  [ 41  40  42]]

 [[139 140 150]
  [135 136 146]
  [133 134 144]
  ...
  [ 41  40  42]
  [ 41  40  42]
  [ 40  39  41]]]
(320, 320)
[[[ 27  27  25]
  [ 27  27  25]
  [ 29  29  27]
  ...
  [ 16  19  19]
  [ 14  19  19]
  [ 12  17  17]]

 [[ 29  29  27]
  [ 29  29  27]
  [ 29  29  27]
  ...
  [ 16  19  19]
  [ 14  19  19]
  [ 12  17  17]]

 [[ 29  29  27]
  [ 29  29  27]
  [ 29  29  27]
  ...
  [ 16  19  19]
  [ 13  18  18]
  [ 12  17  17]]

 ...

 [[130 130 142]
  [131 131 143]
  [135 13

In [ ]:
vidcap = cv2.VideoCapture('video_nurbu.mp4')
success,imagenBruta = vidcap.read()
count = 0
#cv2.namedWindow("cv_image", cv2.WINDOW_NORMAL)
while success:
    image = Image.fromarray(imagenBruta).convert('RGB')
    #cv_image = imagenBruta.convert('RGB')
    cv2.namedWindow("cv_image", cv2.WINDOW_NORMAL)
    cv2.imshow("cv_image",np.array(image))
    sleep(0.15)
    #cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      
    success,imagenBruta = vidcap.read()
    print('Read a new frame: ', success)
    count += 1